translate/translate

- docs/commands/index.rst
- docs/commands/resx2po.rst
- docs/formats/index.rst
- docs/formats/resx.rst
- translate/convert/po2resx.py
- translate/convert/resx2po.py
- translate/convert/test_po2resx.py
- translate/convert/test_resx2po.py
- translate/storage/resx.py
- translate/storage/test_resx.py
Adding support for .Net Resource (.resx) files, which resolves issue #396.
> Add support to convert .Net Resource (.resx) files - resx2po and po2resx

- tests/cli/data/test_pofilter_listfilters/stdout.txt
- translate/filters/checks.py
- translate/filters/pofilter.py
Necessary to programmatically craft the quality checks descriptions staticpage on Pootle.
@dwaynebailey Please review.
> Checks: Expand docstrings to include more detailed descriptions

- translate/lang/data.py
The correct expression can be confirmed in http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html
> data.py: Fix pt_BR Plural-Forms expression

- translate/lang/test_ja.py
Signed-off-by: Hiroshi Miura <miurahr@linux.com>
> add japanese lang test

- translate/storage/fpo.py
This code was deprecated since 2009 (ba8e61b93ef0).
> Removed obsolete code in fpo.py

- translate/storage/cpo.py
- translate/storage/test_cpo.py
Fixes #3206. Thanks Stuart Prescott for the report.
> Fixed wrong usage of importorskip

- translate/convert/idml2po.py
- translate/convert/po2idml.py
- translate/convert/xliff2odf.py
- translate/lang/identify.py
- translate/storage/base.py
Two more commits related to file opening...
> Opening files (follow-up)

- translate/misc/multistring.py
- translate/search/match.py
- translate/storage/placeables/terminology.py
- translate/tools/poterminology.py
- translate/tools/test_poterminology.py
Also added basic tests for poterminology so some of the changed cmp functions are covered by tests.
> Replaced cmp() by new sorting constructs

- translate/storage/poparser.py
Try to convert to unicode as soon as possible.
> Adapted poparsing encoding strategy

- translate/misc/wStringIO.py
- translate/storage/base.py
- translate/storage/factory.py
- translate/storage/wordfast.py
This is in line with commit 2f889c19e2.
Also marked with b/bytes some more strings.
> Use binary mode to open files in base storage

- translate/storage/pocommon.py
- translate/storage/pypo.py
- translate/storage/test_pypo.py
This is a follow-up commit of 0199313bd63.
> Made pypo.pounit encoding agnostic

- translate/search/indexing/PyLuceneIndexer.py
- translate/search/indexing/XapianIndexer.py
- translate/services/tmserver.py
Those were triggered by the docs build.
> Fixed remaining Python3 import issues

- .travis.yml
- docs/commands/pofilter_tests.rst
- docs/releases/dev.rst
- requirements/dev.txt
- translate/filters/checks.py
- translate/filters/test_checks.py
- translate/lang/ar.py
- translate/lang/bn.py
- translate/lang/code_as.py
- translate/lang/common.py
- translate/lang/fa.py
- translate/lang/factory.py
References translate/pootle#4203
> Handle non latin numbers in numbers check

- translate/convert/test_po2json.py
- translate/storage/jsonl10n.py
Followon form 219708fa2d1c44c57aa5eebc8e3edb533d3bdf3e for back conversion.
Fixes #3394
> JSON: keep order when serializing

- docs/commands/index.rst
- docs/commands/tbx2po.rst
- docs/formats/tbx.rst
- docs/releases/dev.rst
- setup.py
- translate/convert/tbx2po.py
- translate/storage/tbx.py
This adds a basic tbx2po converter.  It's aimed at Microsoft TBX files conversion and nothing much else.
> Add tbx2po

- translate/misc/multistring.py
- translate/misc/test_multistring.py
Fixes #3404.
Thanks Julen Ruiz Aizpuru for the report and the tests.
> Fixed comparison regression with multistrings

- README.rst
- docs/developers/styleguide.rst
- docs/developers/testing.rst
- docs/installation.rst
- setup.py
> Removed some leftover Python 2.6 references

- translate/misc/multistring.py
- translate/misc/test_multistring.py
> Re-added str method for multistring type

- tests/cli/data/test_pocount_po_csv/one.po
- tests/cli/data/test_pocount_po_csv/stdout.txt
- tests/cli/test_pocount_po_csv.sh
- translate/tools/pocount.py
pocount csv header is now in one line, easy to import
> pocount: csv header in one line

- translate/convert/po2prop.py
- translate/convert/test_po2prop.py
Previously partial lines remained
> po2prop: remove full untranslated units if required

- tools/mozilla/moz_l10n_builder.py
- translate/convert/factory.py
- translate/convert/sub2po.py
- translate/misc/ourdom.py
- translate/misc/wsgiserver/wsgiserver2.py
- translate/misc/wsgiserver/wsgiserver3.py
- translate/search/indexing/CommonIndexer.py
- translate/storage/ini.py
- translate/storage/lisa.py
- translate/storage/mozilla_lang.py
- translate/storage/poxliff.py
- translate/storage/subtitles.py
- translate/tools/podebug.py
These are low-hanging fruits from landscape.io error summary.
> Fixed syntax issues

- translate/misc/optrecurse.py
- translate/tools/poconflicts.py
- translate/tools/porestructure.py
- translate/tools/poterminology.py
This small refactoring is a step in making the RecursiveOptionParser class a bit lighter and more manageable.
> Separate ProgressBar from RecursiveOptionParser

- requirements/optional.txt
This brings better Python 3 support and lots of bugfixes
> Bump Babel requirement

- translate/storage/mozilla_lang.py
- translate/storage/test_mozilla_lang.py
Adds support for moz_lang headers, and tag comments
> Moz lang headers

- translate/storage/mozilla_lang.py
- translate/storage/test_mozilla_lang.py
* Remember line endings - \n is prefered but \r\n is accepted
> .lang fixes

- translate/filters/checks.py
- translate/filters/test_checks.py
Adds l20ncheker for simple strings and exclude some checks for complex l20n entities.
> Add l20nchecker

- translate/convert/test_po2ts.py
- translate/storage/cpo.py
- translate/storage/fpo.py
- translate/storage/pocommon.py
- translate/storage/pypo.py
- translate/storage/test_cpo.py
- translate/storage/test_po.py
- translate/storage/test_pypo.py
This is to get #3447 fixed.
PRing just to see if Travis passes.
> Revert no po duplicates

- translate/convert/sub2po.py
> sub2po: fixed method name in merge_store

- translate/storage/l20n.py
- translate/storage/test_l20n.py
Add variants and traits support to l20n parser.
Fixes #3519.
> Add variants and traits support for l20nfile

- translate/filters/checks.py
- translate/storage/l20n.py
> Add l20n validation check to L20nChecker

- requirements/dev.txt
v1.5.0 has errors that need fixing
> Req: pin Sphinx to v1.4.9

- docs/conf.py
- requirements/dev.txt
- translate/storage/project.py
> WIP Mock docs using Sphinx config option

- docs/commands/json2po.rst
- docs/commands/prop2po.rst
- tests/cli/data/test_po2json_files_removeuntranslated/out.json
- tests/cli/data/test_po2json_files_removeuntranslated/template.json
- tests/cli/data/test_po2json_files_removeuntranslated/translations.po
- tests/cli/test_po2json_files_removeuntranslated.sh
- translate/convert/convert.py
- translate/convert/po2dtd.py
- translate/convert/po2json.py
- translate/convert/po2moz.py
- translate/convert/po2prop.py
This replaces the `json2po` part of #3266.
> More remove untranslated

- translate/storage/mozilla_lang.py
> Add location_root to lang parser to strip filepath from location

- translate/storage/test_xliff.py
- translate/storage/xliff.py
Relates to https://github.com/translate/pootle/issues/5828
> XLIFF ASCII control characters

- translate/filters/test_pofilter.py
- translate/lang/ro.py
- translate/lang/test_ro.py
> Fix RomanianChecker and add tests for Romanian checks in pofilter

- docs/releases/2.1.0.rst
- docs/releases/index.rst
- translate/filters/checks.py
- translate/filters/test_checks.py
Detects $(var) and %@, @1$@ variables
> Checks: add iOS checkerstyle

- tests/cli/data/test_posegment/one.po
- tests/cli/data/test_posegment/out.po
- tests/cli/test_posegment.sh
- translate/tools/posegment.py
I just saw this bug. I think this is the first time I use several of the new developer infrastructure, so please say if there are better ways of doing this.
> Don't output duplicate header

- translate/storage/properties.py
- translate/storage/test_properties.py
See https://docs.joomla.org/Specification_of_language_files for specification.
> Add support for Joomla dialect

- translate/search/indexing/XapianIndexer.py
Xapian's flintlock is not a lock file whose presence indicates that the
lock is held, but rather a file which is locked using fcntl() locking.
Such locks are automatically released by the OS when the process holding
them terminates, so there's no such thing as a "stale lock", and the
flintlock file should always exist.
If you delete the lockfile and there's an existing writer holding the
lock, it'll still believe it holds the lock but now a second writer can
now also get the lock - if both writers try to update the database, the
result will be database corruption.
Fixes #3581.
> Avoid potential Xapian database corruption

- translate/lang/data.py
There has been change in past to make the equation easier to use - the
new one honors ordering. See launchpad for more disussion on the topic:
https://answers.launchpad.net/launchpad/+question/18324
The new formula also matches CLRD, see #3578.
> Adjusted Slovenian plural equation

- translate/storage/test_php.py
> PHP: Add test for newline between key and value in array

- README.rst
- requirements/recommended.txt
- translate/lang/data.py
- translate/lang/test_data.py
Use pycountry to retrieve language names translations
Partial fix for https://github.com/translate/pootle/issues/6218
> Use pycountry to retrieve language names translations

- translate/lang/data.py
no longer uses module dict for caching as resolving these functions seems to be reasonably fast
> Refactor functions for resolving iso639/3166 translation

- translate/filters/checks.py
- translate/filters/test_checks.py
This adds one more checker on top of #3645.
> Reduced tests

- translate/filters/checks.py
This should have been part of #3648, but I forgot.
> Added reduced checker to the projectcheckers list

- translate/convert/po2txt.py
- translate/convert/test_po2txt.py
This is a slightly different fix from that proposed in #3655 and includes a test.
> Don't use obsolete messages in po2txt

- translate/convert/odf2xliff.py
- translate/convert/oo2xliff.py
- translate/convert/po2oo.py
- translate/convert/po2txt.py
- translate/convert/po2xliff.py
- translate/convert/xliff2oo.py
- translate/tools/poclean.py
- translate/tools/pocompile.py
- translate/tools/podebug.py
- translate/tools/pomerge.py
- translate/tools/posegment.py
- translate/tools/pretranslate.py
> Allow to use .xliff extension everywhere

- translate/lang/factory.py
- translate/lang/test_factory.py
This PR is to address https://github.com/translate/pootle/pull/6542/files#r125042772
> Add function to retrieve all languages

- translate/storage/jsonl10n.py
- translate/storage/test_jsonl10n.py
See following URLs for format docs:
* https://developer.chrome.com/extensions/i18n
* https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization
> Add basic support for WebExtension JSON

- translate/storage/jsonl10n.py
- translate/storage/test_jsonl10n.py
Apparently the description is optional here, so let's not fail if it is not present.
> Correctly handle webextension without description

- .travis.yml
- docs/commands/podebug.rst
- requirements/dev.txt
I've noticed these while working on https://github.com/translate/translate/pull/3674
> Fix Sphinx build errors

- translate/storage/jsonl10n.py
- translate/storage/test_jsonl10n.py
This is basically JSON with additional semantics to handle plurals.
I've done some refactoring in JSON format to avoid too much code duplication.
> Add support for i18next format with plurals

- translate/storage/mo.py
- translate/storage/test_mo.py
To make the API consistent.
Fixes #3441
> Add setcontext to mo file

- translate/storage/test_jsonl10n.py
This was not really covered by tests.
> Add test for filtering in json

- translate/storage/jsonl10n.py
- share most of the code among different variants
- avoid storing internal representation, what did lead to storing whole
JSON dictionary for every unit on flat files
- the `__str__` for unit now returns something reasonable
> Simplify handling of JSON files

- translate/convert/php2po.py
- translate/convert/po2php.py
- translate/convert/test_php2po.py
- translate/convert/test_po2php.py
- translate/storage/php.py
- translate/storage/test_php.py
While working with PHP parser, I've noticed some minor issues with it, mostly invalid PHP code used in tests or generated by tests.
> PHP testsuite fixes and improvements

- translate/storage/test_yaml.py
- translate/storage/yaml.py
> YAML: Gracefully handle adding nested keys in place of values

- translate/convert/pot2po.py
- translate/misc/multistring.py
- translate/misc/test_multistring.py
- translate/storage/aresource.py
- translate/storage/poxliff.py
- translate/storage/test_aresource.py
- translate/storage/test_cpo.py
- translate/storage/test_jsonl10n.py
- translate/storage/test_poxliff.py
- translate/storage/test_pypo.py
- translate/storage/ts2.py
See https://github.com/translate/translate/issues/3681
> Cleanup: Pass unicode strings to multistring

- translate/convert/test_txt2po.py
- translate/convert/txt2po.py
- translate/storage/test_txt.py
- translate/storage/txt.py
> Add test for no segmentation in txt

- translate/storage/test_jsonl10n.py
Adding new unit is not really covered by existing tests.
> Add test for adding i18next plurals

- docs/installation.rst
This is best approach for this.
See #3701
> Use pip for editable installation

- requirements/optional.txt
- translate/storage/php.py
- translate/storage/test_php.py
Current PHP parser is really problematic, so how about using some real parser for PHP?
I've tried to base on https://github.com/viraptor/phply. ~~There are some tricky parts to solve (naming of units is slightly different and comments extraction does not work), but I'd like to get some feedback before spending more time on this.~~ It tries to be as much compatible as possible, but I've decided to change comments handling, see https://github.com/translate/translate/pull/3697#issuecomment-332743699 for more details.
This bases on https://github.com/translate/translate/pull/3696 to get fixed some errors in tests.
Fixes #1685
Fixes #1898
Fixes #1929
Fixes #2611
Fixes #2612
Fixes #2647
Fixes #2648
Fixes #3608
Fixes #3625
Fixes #3626
Fixes #3627
Fixes #3628
Fixes #3629
> Use phply for parsing PHP files

- translate/storage/test_pypo.py
Cleanup based on feedback in #3773
> Remove not needed print functions in pypo test

- requirements/optional.txt
- translate/storage/php.py
Rely on new API introduced in https://github.com/viraptor/phply/pull/45
and make the code much simpler.
> PHP: Simplify lexer code

- translate/storage/aresource.py
- translate/storage/base.py
- translate/storage/catkeys.py
- translate/storage/cpo.py
- translate/storage/dtd.py
- translate/storage/fpo.py
- translate/storage/jsonl10n.py
- translate/storage/l20n.py
- translate/storage/lisa.py
- translate/storage/omegat.py
- translate/storage/php.py
- translate/storage/poxliff.py
- translate/storage/properties.py
- translate/storage/pypo.py
- translate/storage/rc.py
- translate/storage/resx.py
- translate/storage/test_xliff.py
- translate/storage/ts2.py
- translate/storage/txt.py
- translate/storage/utx.py
- translate/storage/wordfast.py
> Deprecate `gettarget` and `settarget` in favor of `target` property

- translate/convert/test_php2po.py
- translate/storage/php.py
- translate/storage/test_php.py
Improve handling of some corner cases in PHP:
* Correctly serialize [] style arrays
* Correctly parse and serialize return statements
> Improve handling of return and array in PHP

- translate/storage/rc.py
- translate/storage/test_rc.py
> Ignore \r characters in RC files.

- translate/convert/test_po2yaml.py
- translate/convert/test_yaml2po.py
- translate/storage/test_yaml.py
- translate/storage/yaml.py
See https://github.com/WeblateOrg/weblate/issues/2128
> YAML: Fix serialization of empty keys

- translate/storage/jsonl10n.py
- translate/storage/test_jsonl10n.py
They are properly parsed, but the structure was not restored on
serializing.
> JSON: Fix serializing of JSON arrays

- translate/storage/aresource.py
- translate/storage/test_aresource.py
Several tweaks to make the output consistent with files generated by Android Studio.
> Android: Consistency with Android Studio

- translate/storage/jsonl10n.py
- translate/storage/test_jsonl10n.py
The placeholders were removed on saving, see https://github.com/WeblateOrg/weblate/issues/2457.
> Fix roundtrip of WebExtension JSON with placeholders

- setup.py
The author_email is probably not working, but I have no clue what to put in.
> Add issue tracker and documentation urls to setup

- docs/formats/yaml.rst
- translate/storage/test_yaml.py
- translate/storage/yaml.py
> Ruby YAML: Add support for plurals

- .gitignore
- translate/storage/test_ts2.py
- translate/storage/ts2.py
> TS: Add support for type="vanished" as type="obsolete" for Qt 5

- translate/storage/poheader.py
- translate/storage/test_pypo.py
> PO: Allow unicode in po headers

- translate/storage/test_yaml.py
- translate/storage/yaml.py
> YAML: Fix handling dict in list

- translate/storage/flatxml.py
This provides API compatibility with LISA based storages.
> FlatXML: Rename element attribute

- translate/convert/test_ts2po.py
- translate/convert/ts2po.py
Also update ts2po to use the ts2 storage module.
> In ts2po, add support for converting disambiguation notes and comments

- docs/formats/yaml.rst
- translate/storage/test_yaml.py
- translate/storage/yaml.py
Adds customization to YAML parser and fixes most of the xfail tests.
> Improve YAML compliance

- translate/convert/prop2po.py
This is cleaner approach than returing specific string in this case.
Fixes #3939
> prop2po: Use an exception to indicate unit to discard

- translate/storage/poparser.py
- translate/storage/pypo.py
* Avoid building strings in place
* Use any + chain instead of iterating over temporarily created array
* Remove not needed else statements
* Avoid using len() as boolean condition
* Directly return bool instead of using if
> pypo: Performance and code cleanup

- translate/storage/pypo.py
- translate/storage/test_poheader.py
Should address https://github.com/translate/translate/pull/3936#issuecomment-589541155
> pypo: Avoid adding extra space on empty comment lines

- translate/storage/test_ts2.py
- translate/storage/ts2.py
I see no good reason to duplicate the data.
> ts2: Avoid duplicating plurals definition

- .github/workflows/setup.yml
- docs/api/index.rst
- docs/conf.py
- docs/developers/releasing.rst
- translate/search/indexing/XapianIndexer.py
Add some basic tests for creating distribution and verifying it is built correctly.
Also fixes several issues found by this.
> Setup tests

- README.rst
- docs/formats/ini.rst
- requirements/optional.txt
It is now Python 3 compatible.
> ini: bump iniparse dependency

- requirements/dev.txt
- requirements/optional.txt
This is non-breaking version of https://github.com/translate/translate/pull/3968
The dependabot handles correctly python version limitations so it was pretty much painless, based on following pull requests:
* https://github.com/nijel/translate/pull/7
* https://github.com/nijel/translate/pull/6
* https://github.com/nijel/translate/pull/5
* https://github.com/nijel/translate/pull/4
> Dependencies update

- .github/workflows/setup.yml
Followup for https://github.com/translate/translate/pull/3977
> Use native submodules support

- .github/workflows/lint.yml
Also included the setup.cfg which seems to hold the settings.
> chore: Only run lint if python files are changed

- .github/workflows/docs.yml
Skips the build for PRs that don't touch anything related to the docs.
> chore: Only build docs on change

- translate/convert/csv2po.py
- translate/convert/po2symb.py
- translate/filters/checks.py
- translate/filters/decoration.py
- translate/filters/prefilters.py
- translate/lang/ngram.py
- translate/lang/team.py
- translate/misc/optrecurse.py
- translate/search/match.py
- translate/storage/dtd.py
- translate/storage/html.py
- translate/storage/oo.py
- translate/storage/placeables/strelem.py
- translate/storage/properties.py
- translate/storage/rc.py
- translate/storage/statsdb.py
- translate/storage/tmdb.py
- translate/storage/trados.py
- translate/storage/txt.py
- translate/storage/xml_extract/generate.py
- translate/storage/xml_extract/misc.py
- translate/tools/phppo2pypo.py
- translate/tools/poclean.py
- translate/tools/pypo2phppo.py
In most cases this is a warning, but in some setups it can be error as well, see https://github.com/translate/translate/runs/610261179?check_suite_focus=true#step:8:13
> Fix invalid escape sequence warnings

- .github/workflows/linux.yml
- .github/workflows/osx.yml
- .github/workflows/win.yml
- translate/misc/selector.py
Nothing wrong with the current approach, was just playing with the filtering.
Also noticed that the VScode linter doesn't like the interpolation for the `runs-on` value
> OS specifc GitHub Actions

- README.rst
Replace requires.io badge for dependabot one, fix pypi badge alt text.
> readme: Update badges

- translate/storage/lisa.py
- translate/storage/test_xliff.py
The case when there are no language nodes is properly handled in the
code, remove the assertion.
> lisa: remove not needed assertion

- docs/releases/2.5.1.rst
I've messed up this, see https://github.com/translate/translate/issues/3966#issuecomment-619376651
> docs: Fix release notes indentation

- docs/developers/releasing.rst
- adjust list of files with version number
- adjust website files to update
- remove no longer used announcement steps
> docs: Update releasing instructions

- translate/storage/poxliff.py
- translate/storage/test_poxliff.py
It is used in the real world and the specification is not clear on this.
> poxliff: support non numeric ids on plurals

- docs/formats/resx.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translate/translate/4001)
> Fix spelling of "prefixed"

- translate/misc/test_multistring.py
Addresses https://github.com/translate/translate/pull/3999#issuecomment-621656740
> multistring: Remove string prefix from tests

- docs/formats/php.rst
- translate/storage/php.py
- translate/storage/test_php.py
* Handle some missing syntax
* Improve keeping quoting style
* Add support for Laravel plurals
> PHP improvements

- setup.py
- translate/convert/convert.py
- translate/convert/po2moz.py
- translate/filters/checks.py
- translate/filters/pofilter.py
- translate/lang/scn.py
- translate/misc/lru.py
- translate/misc/optrecurse.py
- translate/misc/progressbar.py
- translate/search/match.py
- translate/storage/fpo.py
- translate/storage/html.py
- translate/storage/mozilla_lang.py
- translate/storage/pypo.py
- translate/storage/resx.py
- translate/storage/ts2.py
- translate/storage/xliff.py
> Use super() to call parent class method

- .github/workflows/setup.yml
- install wheel to utilize pip cache
- collect coverage for setup.py invocation to see what is not tested
> CI: Improve setup.py testing

- README.rst
- docs/installation.rst
- requirements/optional.txt
- requirements/recommended.txt
- setup.py
The full version can be installed by:
pip install translate-toolkit[all]
See #4004
> Setup: Allow to specify optional deps using pip

- translate/convert/po2prop.py
- translate/convert/prop2po.py
- translate/convert/test_po2prop.py
- translate/convert/test_prop2po.py
- translate/storage/properties.py
- translate/storage/test_properties.py
Rebased and fixed https://github.com/translate/translate/pull/3885
> GWT personality

- docs/formats/json.rst
- translate/storage/jsonl10n.py
- translate/storage/test_jsonl10n.py
Fixes  #3910 
Also requested at https://github.com/WeblateOrg/weblate/issues/2847
> json: Add support for ARB files

- requirements/optional.txt
- translate/convert/po2rc.py
- translate/convert/rc2po.py
- translate/convert/test_po2rc.py
- translate/convert/test_rc2po.py
- translate/storage/rc.py
- translate/storage/test_rc.py
I've rebased and squashed changes from https://github.com/translate/translate/compare/master...PhoneixS:pyparsing-rc created originally by @PhoneixS
See https://github.com/translate/translate/issues/3204
What was omitted:
* https://github.com/translate/translate/commit/284324221f539f725d6b0e9e797752c997584f2e seems unrelated and in case it is needed should go to separate PR
* https://github.com/translate/translate/commit/d0b988f1164b902db9717e7e90283c18fcb96a1c changes many lines and seems to do no functional changes
> rc: Changed parsing to use Pyparsing library to get a better aproach.

- translate/convert/test_po2oo.py
- translate/filters/pofilter.py
- translate/filters/test_pofilter.py
- translate/services/tmserver.py
- translate/storage/test_cpo.py
- translate/tools/pydiff.py
~~Work in progress, there are more things to fix.~~
> Fix undefined variables

- translate/convert/po2symb.py
- translate/convert/symb2po.py
- translate/storage/bundleprojstore.py
- translate/storage/placeables/base.py
Only import symbols code uses, that way it is easier to find what is coming
from which module.
> Avoid using wildcard imports

- tools/mozilla/get_moz_enUS.py
Fixes #4065
I have no clue if these tools are still useful. Maybe it's better to drop tools/mozilla altogether?
> tools: Fix execution with Python 3

- translate/storage/jsonl10n.py
- translate/storage/test_jsonl10n.py
The members of single dict were wrongly inserted as separate list
members.
> json: Fix serializing of dict inside list

- translate/storage/properties.py
- translate/storage/test_properties.py
Small fix for the new XWiki Page Properties format.
> fix: line return in XWiki Page Properties format.

- translate/storage/rc.py
- translate/storage/test_rc.py
> rc: Fix parsing adjancent strings

- translate/convert/po2rc.py
- translate/storage/rc.py
- translate/storage/test_rc.py
Fixes https://github.com/translate/translate/issues/4112
> rc: fix empty strings handling

- translate/__version__.py
Make the release process simpler and include just one version number
and generate all others from that one.
> version: generate other version formats dynamically

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- docs/developers/styleguide.rst
- requirements/dev.txt
This is just initial introduction without enforcing any important rules,
these will be added separately.
> lint: Introduce pre-commit for linting

- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/linux.yml
- .github/workflows/osx.yml
- .github/workflows/setup.yml
- .github/workflows/win.yml
The path was wrong leading to not updated and purged caches.
> ci: Fix cache key based on deps

- .github/matchers/flake8.json
- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- requirements/dev.txt
- setup.cfg
- tests/xliff_conformance/test_xliff_conformance.py
- tools/mozilla/buildxpi.py
- tools/mozilla/moz_l10n_builder.py
- translate/storage/qm.py
- translate/storage/test_properties.py
Fixed failing code (mostly unused variables or imports) and adjusted
configuration.
> lint: Add flake8 linter to pre-commit

- translate/storage/aresource.py
- translate/storage/test_aresource.py
The patched doctype needs to be applied when serializing as well.
Fixes #4135
> android: Fix adding units with entities

- docs/developers/styleguide.rst
See https://github.com/translate/translate/pull/4069
> docs: Bring back styleguide example

- translate/storage/test_yaml.py
- translate/storage/yaml.py
It seems to be used in some corner cases.
Fixes https://github.com/WeblateOrg/weblate/issues/4765
> yaml: handle TaggedScalar type while parsing

- translate/storage/base.py
- translate/storage/jsonl10n.py
- translate/storage/test_jsonl10n.py
Fixes https://github.com/WeblateOrg/weblate/issues/4854
> json: Fix serializing files with list as root element

- .github/workflows/docs.yml
- .github/workflows/linux.yml
- .github/workflows/osx.yml
- .github/workflows/pre-commit.yml
- .github/workflows/win.yml
- docs/conf.py
- docs/installation.rst
- setup.py
* Adjust CI tests to cover Python 3.9
* List 3.9 in classifiers
* Use Python 3.9 in the documentation
> misc: Add support for Python 3.9

- .github/workflows/osx.yml
- translate/storage/base.py
- translate/storage/test_jsonl10n.py
- fixed string IDs parsing when list is used
- gracefully handle sparse lists
> json: Improved handling of newly added keys to list

- .github/workflows/osx.yml
See https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
> CI: Use new approach for extending search path

- .github/workflows/linux.yml
- .github/workflows/osx.yml
- .github/workflows/win.yml
- Makefile
It also fixes its invocation in Makefile.
CC @Jibec, see https://github.com/translate/translate/pull/4188#issuecomment-742113158
> ci: Use make test instead od ivoking pytest manually

- translate/storage/xliff.py
This is the only place where it is needed and there is no reason to slow
down the switchfile just to make potential call to addsourceunit faster.
It doesn't address the TODO in the code, that would change the behaviour and I'm not sure if we can do it safely.
> xliff: move messagenum calculation to addsourceunit

- tests/cli/data/test_pocount_po_fuzzy/one.po
- tests/cli/data/test_pocount_po_fuzzy/stdout.txt
- tests/cli/data/test_pocount_po_plurals/plural.po
- tests/cli/data/test_pocount_po_plurals/stdout.txt
- tests/cli/data/test_pocount_xliff_states_no/states.xlf
- tests/cli/data/test_pocount_xliff_states_no/stdout.txt
- tests/cli/data/test_pocount_xliff_states_yes/states.xlf
- tests/cli/data/test_pocount_xliff_states_yes/stdout.txt
- tests/cli/test_pocount_po_fuzzy.sh
- tests/cli/test_pocount_xliff_states_no.sh
- tests/cli/test_pocount_xliff_states_yes.sh
in continuation of https://github.com/translate/translate/pull/4188#issuecomment-743056848
could you please tell me what are realistic combination in xliff files? what does approved means in a trans-unit?
the current output results doesn't seems correct to me, I'm a little bit confused.
> test po fuzzy & plurals, and xlif states

- translate/storage/test_xliff.py
- translate/storage/xliff.py
Otherwise the whitespace might be lost.
Fixes https://github.com/WeblateOrg/weblate/issues/5026
> xliff: Ensure xml:space="preserve" is set when updating target

- translate/storage/mo.py
- translate/storage/test_mo.py
* Consistent hash table size calculation
* Skip headers gettext skips
* Fix hash table calculation for plural strings
Fixes https://github.com/WeblateOrg/weblate/issues/5098
> mo: improved gettext compatibility

- .github/workflows/linux.yml
Otherwise the installed files for the functional tests are out of collected coverage path.
> tests: Use editable install to collect functional tests coverage

- translate/storage/subtitles.py
- translate/storage/test_subtitles.py
The tests pass since aeidon 1.9, see #4222.
Fixes #4155
> subtitle: Enable and fix tests

- translate/storage/test_base.py
- translate/storage/test_monolingual.py
It is not really useful - pytest shows the output only in case of failure,
so better to remove the condition and avoid having failure only branch
which would be never tested and could contain bugs.
> test: Remove condtion prior to assert

- translate/storage/jsonl10n.py
- translate/storage/test_jsonl10n.py
- translate/storage/yaml.py
These would become out of sync causing troubles when creating new units.
> json: Reset unitid on changeing id

- translate/convert/csv2po.py
- translate/convert/po2csv.py
- translate/convert/test_csv2po.py
- translate/convert/test_po2csv.py
This is followup to https://github.com/translate/translate/pull/4239 by @slide333333 with fixed coding style and added tests.
> Fix columnorder argument for csv2po/po2csv

- translate/storage/php.py
- translate/storage/test_php.py
- translate/storage/test_po.py
Fixes https://github.com/WeblateOrg/weblate/issues/5295
> php: Sanitize new unit key to produce valid PHP syntax

- translate/storage/cpo.py
Perform the removal in the finally block to avoid leaving the temporary
files around.
> cpo: cleanup temporary files in case of exception

- translate/convert/po2php.py
- translate/convert/test_po2php.py
* Avoid reimplementing parser and serializer and use phpfile for that.
* This ensures compatibility with php2po output (fixes #3909)
* This breaks some of the existing behaviour though:
* Additional PHP statements are stripped from the file
* Some whitespace is not preserved
> po2php: Use phpfile as a serializer

- translate/storage/pypo.py
- Drop Python 2 compatibility
- Look for "msgid " to avoid false positives
> po: Improve newline detection

- translate/storage/poparser.py
- translate/storage/test_po.py
> pypo: Improve previous msgid parsing

- translate/storage/pypo.py
- translate/storage/test_pypo.py
See https://github.com/WeblateOrg/weblate/issues/5695
Work in progress, right now this only adds failing tests.
> po: Fix newlines round-trip

- docs/commands/podebug.rst
Documented the feature from https://github.com/translate/translate/pull/3522
I could not find this anywhere in the docs.
> Added --preserveplaceholders documentation to podebug.rst

- translate/storage/pypo.py
- translate/storage/test_pypo.py
Do not look inside comments when looking for first msgid.
Fixes #4308
> po: Improve newline char detection

- translate/storage/properties.py
Tiny optimizations and code cleanup.
> Properties code cleanup

- translate/storage/properties.py
Several optimizations of the properties parser.
> Properties: Performance improvements

- requirements/dev.txt
- translate/convert/csv2po.py
- translate/convert/po2txt.py
- translate/filters/checks.py
- translate/misc/optrecurse.py
- translate/misc/ourdom.py
- translate/storage/aresource.py
- translate/storage/base.py
- translate/storage/benchmark.py
- translate/storage/cpo.py
- translate/storage/fpo.py
- translate/storage/oo.py
- translate/storage/php.py
- translate/storage/placeables/strelem.py
- translate/storage/placeables/test_base.py
- translate/storage/placeables/xliff.py
- translate/storage/pypo.py
- translate/storage/test_html.py
- translate/storage/ts.py
- translate/storage/ts2.py
- translate/storage/txt.py
- translate/tools/poconflicts.py
- translate/tools/podebug.py
- translate/tools/pogrep.py
- translate/tools/porestructure.py
- translate/tools/poterminology.py
- translate/tools/pydiff.py
Contains https://github.com/translate/translate/pull/4354 and fixes generated by it.
> Pyupgrade update and fixes

- requirements/optional.txt
- translate/storage/factory.py
- translate/storage/fluent.py
- translate/storage/test_fluent.py
This is followup to https://github.com/translate/translate/pull/4378
> Add basic Fluent storage support, take two

- translate/storage/stringsdict.py
- translate/storage/test_stringsdict.py
Hopefully fixes https://github.com/WeblateOrg/weblate/issues/6418
> stringsdict: Detect base files as English

- translate/storage/rc.py
- translate/storage/test_rc.py
* Fixed detection of quoted controls
* Fixed parsing of blocks with comments inside
> RC parser fixes

- translate/storage/fluent.py
- translate/storage/test_fluent.py
Closes translate/translate#4429.
> Fluent: Fix serialization of standalone comments

- translate/convert/po2rc.py
- translate/storage/rc.py
See https://github.com/pyparsing/pyparsing/issues/323
> rc: Parser fixes for negative lookup

- .github/workflows/docs.yml
- .github/workflows/linux.yml
- .github/workflows/osx.yml
- .github/workflows/pre-commit.yml
- .github/workflows/setup.yml
- .github/workflows/win.yml
We can reuse the logic instead of having own one.
> ci: Use caching in actions/setup-python

- translate/storage/test_yaml.py
- translate/storage/yaml.py
Fixes https://github.com/WeblateOrg/weblate/issues/7015
> yaml: Fixed adding strings to empty Ruby YAML file

- translate/storage/poparser.py
Include current line causing error and always include line number. This
allows to better understand what is wrong in the file.
> po: Provide more useful error messages

- translate/storage/pypo.py
- translate/storage/test_po.py
The implementation is based on https://bugs.python.org/issue24665 while
removing support for TextWrap features we do not need.
Fixes #4452
> pypo: Fixed line wrapping with full width characters

- translate/convert/po2rc.py
This is both faster and more readable.
> po2rc: Use yield instead of iteratively building list

- .github/dependabot.yml
- .github/workflows/docs.yml
- .github/workflows/linux.yml
- .github/workflows/osx.yml
- .github/workflows/pre-commit.yml
- .github/workflows/setup.yml
- .github/workflows/win.yml
- .pre-commit-config.yaml
This ensures that yaml configurations for CI are consistently formatted.
> ci: Add yaml formatter to pre-commit

- translate/storage/csvl10n.py
Use any() and get() makes the code more readable and removes
extra dictionary acces for every field.
> csv: Use any to validate field names

- translate/storage/lisa.py
I've mistakenly introduced this in
10596adabc63725fd8c13cd7fbe84bfcd76146a2.
> lisa: Remove unreachable code

- translate/storage/mo.py
- translate/storage/poxliff.py
- translate/storage/properties.py
- translate/storage/txt.py
- translate/storage/xliff.py
Fixes some pylint W0612 warnings.
> Remove some unused loop vars

- translate/storage/poxliff.py
> Poxliff cleanup

- translate/storage/properties.py
- use staticmethod where applicable
- add type hints
- improve variable names
- avoid using else after return
- avoid repeatedly concatenating strings
> properties: Code cleanup

- translate/misc/xml_helpers.py
- use f-strings
- avoid else after return
- avoid repeated ord() invocation
- add type hints
> misc: Cleanup xml helpers

- tools/mozilla/buildxpi.py
- translate/convert/convert.py
- translate/convert/po2oo.py
- translate/convert/po2prop.py
- translate/convert/xliff2oo.py
- translate/filters/checks.py
- translate/lang/scn.py
- translate/storage/dtd.py
- translate/storage/poheader.py
- translate/storage/pypo.py
- translate/storage/ts2.py
- translate/tools/pomerge.py
- avoid else branch after return/raise
- merge two if statements into single one
> chore: Cleanup if statements

- translate/convert/test_html2po.py
- translate/storage/poparser.py
- translate/storage/test_poheader.py
Some blocks were misplaced and not being treated as documentation.
> chore: Fix docblock placement

- .github/dependabot.yml
- .github/workflows/docs.yml
- .github/workflows/linux.yml
- .github/workflows/osx.yml
- .github/workflows/pre-commit.yml
- .github/workflows/setup.yml
- .github/workflows/win.yml
- .pre-commit-config.yaml
> ci: Use more compact YAML formatting

- translate/storage/cpo.py
Properly free gettext structures when needed.
> cpo: Fix memory leaks

- translate/storage/properties.py
- translate/storage/test_properties.py
These do not have to be only plurals, so handle them gracefully.
Fixes #4573
> properties: Improved hadling of keys with [] in gwt

- translate/storage/base.py
- translate/storage/test_jsonl10n.py
See https://github.com/WeblateOrg/weblate/issues/7294
> json: Fixed adding nested array elements manually

- .github/workflows/setup.yml
> ci: Test that installed version can find data

- translate/storage/test_properties.py
Cover serialization as well. I was just unsure it is handled properly, so better to exted the test coverage.
> properties: Add more tests for whitespace handling

- translate/storage/base.py
- translate/storage/test_yaml.py
Remove empty dictionaries which appear after removing last unit.
> yaml: Improve strings removal

- translate/storage/properties.py
- translate/storage/test_properties.py
Fixing #4617, and then https://github.com/WeblateOrg/weblate/issues/7562
> Fixing backslash problems for iOS strings

- translate/storage/flatxml.py
- translate/storage/resourcedictionary.py
- translate/storage/test_resourcedictionary.py
This is based on FlatXML storage and includes changes to make it easier
to modify the behavior in subclasses.
Fixes #4589
> formats: Add support for ResourceDictionary

- translate/storage/txt.py
This performs way better and is easier to read.
> txt: Use f-string istead of join

- docs/formats/strings.rst
> docs: Clarify Strings format specification

- translate/storage/rc.py
- translate/storage/test_rc.py
> rc: Fix parsing comment in MENU

- translate/convert/rc2po.py
- translate/convert/test_rc2po.py
- translate/storage/rc.py
- sync default with rcfile
- make rcfile honor passed encoding for parsing
Alternative fix for https://github.com/translate/translate/pull/4652
@jon-turney can you please check it works for your use case as well?
> rc2po: Honor passed --charset

- translate/storage/test_aresource.py
See https://github.com/WeblateOrg/weblate/issues/7816
> aresource: Test removing plurals in Chinese

- docs/license.rst
> doc: fix GPL link to GPLv2.0

- translate/storage/ini.py
- translate/storage/test_base.py
- translate/storage/test_ini.py
- This now behaves same as JSON or YAML.
- Added tests and fixed some issues discovered by them.
See https://github.com/WeblateOrg/weblate/issues/8214
> ini: Consistent location handling with other monolingual formats

- translate/storage/pypo.py
- translate/storage/test_po.py
It no longer seems to wrap inside plural equation.
Fixes #4745
> po: Adjust wrapping to changes in gettext 0.21.1

- requirements/dev.txt
See https://github.com/translate/translate/pull/4791
> deps: Split up Sphix dep based on Python version

- translate/storage/jsonl10n.py
- translate/storage/test_jsonl10n.py
I started experimenting with this as I'd very much like this to be supported in Weblate, however my Python is extremely rusty, so let me know if anything is amiss.
Fixes #4450
Signed-off-by: Sam Whited <sam@samwhited.com>
> json: support gotext JSON format

- translate/storage/jsonl10n.py
- translate/storage/test_jsonl10n.py
Followup for https://github.com/translate/translate/pull/4720
Fixes https://github.com/translate/translate/issues/4485
>  Add support for the i18next v4 format

- docs/conf.py
> docs: update the year in the copyright footer

- translate/storage/jsonl10n.py
- translate/storage/test_jsonl10n.py
It used all plurals even for languages which do not have them.
> json: Fix parsing i18next v4 plurals

- translate/tools/pocount.py
This splits code into separated stats collection and rendering parse, with each renderer in it's own class.
It should not change any of the outputs, but let's not merge this until #4881 is merged, to be completely safe.
> Refactor pocount

- tests/cli/data/test_pocount_po_csv/stdout.txt
- tests/cli/test_pocount_po_csv.sh
- translate/tools/__snapshots__/test_pocount.ambr
- translate/tools/pocount.py
This refactors csv rendering from hand-written style to using csv module.
Output is changed slightly, but this is expected.
> refactor(pocount): Use csv module for writing csv

- translate/storage/tbx.py
- translate/storage/test_tbx.py
This makes removenotes and addnote consistent with getnotes.
> tbx: Fixed setting different origin of notes

- translate/convert/test_po2rc.py
- translate/storage/rc.py
- translate/storage/test_rc.py
Parse and escape quotes so that the translators do not have to be aware of the file syntax.
> rc: Fix quotes handling

- docs/commands/csv2po.rst
- translate/convert/csv2po.py
- translate/convert/po2csv.py
- translate/convert/test_po2csv.py
> po2csv: preserve context

- translate/storage/tbx.py
- translate/storage/test_tbx.py
This makes it consistent with adding.
See https://github.com/WeblateOrg/weblate/issues/9476
> tbx: Apply filtering when parsing notes

- translate/convert/oo2xliff.py
- translate/convert/xliff2oo.py
This is what addlocation/getlocation used to do before https://github.com/translate/translate/pull/4948
> convert: use id in xliff conversion

- translate/storage/fluent.py
These are just some comments for longevity to help with maintenance.
Small follow up to https://github.com/translate/translate/pull/4963
> fluent: Add some notes for FluentSelectorBranch and FluentSelectorNode

- translate/storage/xml_extract/extract.py
- translate/storage/xml_extract/unit_tree.py
The implementation will change in #4948.
> xml_extract: stop relying on location using ID in xliff

- requirements/optional.txt
- translate/lang/data.py
- translate/lang/test_data.py
- optional dependency makes the code more complex
- not used inside translate-toolkit
- only outside user seems Pootle, which is no longer developed
See also #4950
> lang: remove pycountry dependency

- docs/commands/android2po.rst
- docs/commands/index.rst
- setup.cfg
- translate/convert/android2po.py
- translate/convert/test_android2po.py
> Android2PO conversor - Converts from Android resources to PO file

- translate/storage/test_xliff.py
- translate/storage/xliff.py
- support locations without a line number
- do no crash on locatio with no or multiple :
- avoid using join in tests to actually verify that locations are preserved
> xliff: make location handling more robus

- translate/storage/test_ts2.py
- translate/storage/ts2.py
Relative locations are not really useful for display to users, but are handy for serialization as they produce smaller diff.
> ts2: Expand relative locations

- .github/workflows/linux.yml
- .github/workflows/osx.yml
- .github/workflows/win.yml
> ci: Add Python 3.12 to test matrix

- pyproject.toml
- tests/translate/convert/test_accesskey.py
- tests/translate/convert/test_po2dtd.py
- tests/translate/convert/test_po2oo.py
- tests/translate/storage/placeables/test_base.py
- tests/translate/storage/test_markdown.py
- tests/translate/storage/test_mozilla_lang.py
- tests/translate/storage/test_omegat.py
- tests/translate/tools/test_pocount.py
- tests/xliff_conformance/test_xliff_conformance.py
- translate/misc/ourdom.py
- translate/storage/placeables/strelem.py
- use individual asserts instead of and inside assert
- use tuple for pytest.mark.parametrize
- add explicit reutrn value for change_test_dir fixture
> tets: improve pytest usage

- pyproject.toml
- translate/convert/convert.py
- translate/convert/po2html.py
- translate/convert/po2md.py
- translate/convert/web2py2po.py
- translate/misc/selector.py
- translate/storage/base.py
- translate/storage/cpo.py
- translate/storage/fluent.py
- translate/storage/fpo.py
- translate/storage/project.py
- translate/storage/statistics.py
- translate/storage/yaml.py
- translate/tools/pocount.py
Use comprehensions instead of loops.
> chore: use comprehensions

- pyproject.toml
- translate/misc/xml_helpers.py
- translate/storage/base.py
- translate/storage/fluent.py
- translate/storage/markdown.py
- translate/storage/properties.py
- translate/storage/pypo.py
This makes the code easier to read.
> chore: use future annotations

- pyproject.toml
- translate/convert/xliff2oo.py
- translate/filters/spelling.py
- translate/storage/placeables/strelem.py
- translate/tools/build_tmdb.py
- translate/tools/pocount.py
- properly log exceptions
- use logging formatting instead doing that manually
> chore: logging improvements

- pyproject.toml
- tests/translate/filters/test_pofilter.py
- tests/translate/tools/test_pogrep.py
- tools/mozilla/buildxpi.py
- tools/mozilla/moz_l10n_builder.py
- translate/misc/optrecurse.py
- translate/misc/quote.py
- translate/storage/aresource.py
- translate/storage/base.py
- translate/storage/jsonl10n.py
- translate/storage/mo.py
- translate/storage/oo.py
- translate/storage/php.py
- translate/storage/placeables/__init__.py
- translate/storage/project.py
- translate/storage/rc.py
- translate/storage/yaml.py
This avoids building several itermediate lists to create a one.
> chore: use * to merge lists instead of concatenation

- pyproject.toml
- translate/lang/common.py
- translate/lang/scn.py
- translate/storage/fluent.py
- translate/storage/pocommon.py
- translate/storage/properties.py
- translate/storage/pypo.py
- translate/storage/xliff.py
- translate/tools/podebug.py
Avoid building lists one by one, use comprehensions instead.
> chore: use list comprehensions

- pyproject.toml
- tests/translate/storage/test_fluent.py
- tools/mozilla/moz_l10n_builder.py
- translate/convert/prop2po.py
- translate/misc/file_discovery.py
- translate/misc/optrecurse.py
- translate/storage/base.py
- translate/storage/bundleprojstore.py
- translate/storage/fluent.py
- translate/storage/placeables/strelem.py
- translate/storage/properties.py
- translate/storage/qm.py
- translate/storage/stringsdict.py
- translate/tools/pogrep.py
- use TypeError for invalid types
- use ValueError for invalid values
- use raise without parameter to reraise exception
> chore: improve exception handling

- pyproject.toml
- tools/mozilla/moz_l10n_builder.py
- translate/misc/selector.py
- translate/storage/_factory_classes.py
- translate/storage/bundleprojstore.py
- translate/storage/lisa.py
- translate/storage/placeables/strelem.py
- translate/storage/poxliff.py
- translate/storage/projstore.py
- translate/storage/tmdb.py
- translate/storage/xliff.py
- translate/storage/xml_extract/misc.py
- translate/tools/poterminology.py
It makes code more readable than doing this manually.
> chore: utilize contextlib.suppress

- .github/workflows/setup.yml
- .pre-commit-config.yaml
- docs/developers/releasing.rst
Avoid building and publishing package manually, automate that.
> ci: automate publishing

- translate/lang/data.py
Fixes https://github.com/WeblateOrg/weblate/issues/9364
> lang: Update to CLDR 44

- tests/translate/storage/test_yaml.py
See https://github.com/WeblateOrg/weblate/discussions/10394
> yaml: test quotes round trip

- tests/translate/storage/test_jsonl10n.py
- translate/storage/base.py
- Gracefully handle non-numeric index parts
- Add tests for parsing
- Add __eq__ and __repr__ to UnitId class
> storage: make UnitId parsing more robust

- translate/storage/lisa.py
- translate/storage/resx.py
- translate/storage/ts2.py
This makes the processing simpler and avoid hard-coding encoded bytes.
> lisa: pass string to serialize_hook

- translate/storage/aresource.py
- use sets to test character classes, it performs better
- construct character classes once
- use locals to access frequently used global variables
- remove unused active_percent code path
> aresource: simplify unescape

- tests/translate/storage/test_jsonl10n.py
- translate/storage/jsonl10n.py
> gotext: fix parsing alternative plurals syntax

- docs/formats/json.rst
- tests/translate/storage/test_jsonl10n.py
- translate/storage/jsonl10n.py
> json: Add support for FormatJS

- translate/filters/checks.py
- translate/filters/decoration.py
- translate/storage/dtd.py
- translate/storage/ini.py
- translate/storage/poheader.py
- translate/storage/poxliff.py
- translate/tools/podebug.py
Move out regex compilation to a top-level.
Fixes #2164
> chore: use compiled regex

- tests/translate/storage/test_jsonl10n.py
- translate/storage/jsonl10n.py
See https://github.com/WeblateOrg/weblate/discussions/10864
> json: improved error messages on invalid data

- tests/translate/storage/test_po.py
See #5251 and https://github.com/WeblateOrg/weblate/issues/11615
> tests: add test for wrapping differences compared to gettext

- tests/translate/storage/test_csvl10n.py
- translate/storage/csvl10n.py
This is useful in situations the dialect is known like in https://github.com/WeblateOrg/weblate/issues/11872
> feat(csv): support forcing dialect and skipping automatic detection

- tests/translate/storage/test_pypo.py
- translate/misc/dictutils.py
- translate/storage/poheader.py
- have a single definition of header defaults
- remove not needed methods from cidict
- use more of comprehensions
- use string for tests for better formatted test failures
> chore(poheader): optimize header operations

- tests/translate/misc/test_quote.py
- translate/misc/quote.py
- translate/storage/pypo.py
Use modern Python features as generator and walrus operator to simplify the code.
> chore(quote): simplify find_all

- translate/storage/poparser.py
- translate/storage/pypo.py
- do not compare against a blank list
- measure list length just once
> chore(pypo): optimize some comparisons

- translate/storage/pypo.py
This has about the same performance, but much simpler code.
> feat(pypo): use re to (un)escape strings in PO files

- tests/translate/storage/test_php.py
- translate/storage/php.py
> PHP: escape quotes in keys

- translate/storage/html.py
See https://github.com/WeblateOrg/weblate/discussions/12498
> feat(html): translate <label> tag

- .github/workflows/docs.yml
- .github/workflows/pre-commit.yml
- .github/workflows/setup.yml
- .github/workflows/test.yml
- .readthedocs.yml
This makes installation faster and better caches deps on GitHub.
> chore: use uv to install dependencies

- pyproject.toml
- translate/storage/placeables/__init__.py
This might have unexpected outcome if something changes.
> chore: avoid calculating __all__

- .github/workflows/test.yml
- pyproject.toml
- setup.cfg
- translate/convert/po2rc.py
- translate/misc/quote.py
- translate/misc/selector.py
- translate/storage/aresource.py
- translate/storage/base.py
- translate/storage/fluent.py
- translate/storage/fpo.py
- translate/storage/jsonl10n.py
- translate/storage/markdown.py
- translate/storage/pypo.py
- translate/tools/junitmsgfmt.py
- some dependencies are dropping Python 3.8 support
- use Python 3.9 features
> chore: drop support for Python 3.8

- pyproject.toml
- translate/convert/accesskey.py
- translate/convert/oo2po.py
- translate/convert/oo2xliff.py
- translate/convert/po2prop.py
- translate/filters/autocorrect.py
- translate/lang/data.py
- translate/misc/selector.py
- translate/storage/cpo.py
- translate/storage/mo.py
- translate/storage/omegat.py
- translate/storage/poheader.py
- translate/storage/properties.py
- translate/storage/symbian.py
- translate/storage/utx.py
- translate/storage/xliff.py
- translate/storage/xml_extract/extract.py
- translate/tools/poterminology.py
> chore: simplify testing for an empty string

- translate/filters/checks.py
- translate/filters/decoration.py
- translate/lang/ar.py
- translate/lang/data.py
- translate/lang/fa.py
- translate/lang/fr.py
- translate/lang/nqo.py
- translate/misc/optrecurse.py
- translate/search/match.py
- translate/storage/aresource.py
- translate/storage/cpo.py
- translate/storage/dtd.py
- translate/storage/fluent.py
- translate/storage/ical.py
- translate/storage/ini.py
- translate/storage/mo.py
- translate/storage/placeables/general.py
- translate/storage/pocommon.py
- translate/storage/poheader.py
- translate/storage/poparser.py
- translate/storage/properties.py
- translate/storage/rc.py
- translate/storage/symbian.py
- translate/storage/trados.py
- translate/tools/pocount.py
- translate/tools/podebug.py
This avoids some complex escaping.
> chore: use raw strings for re

- tests/translate/storage/test_po.py
- translate/storage/pypo.py
> feat(pypo): consistent braces wrapping with gettext

- translate/storage/aresource.py
It performs much better than character based one, especially for long strings.
> fix(android): use regex based decoder

- tests/translate/storage/test_aresource.py
- translate/storage/aresource.py
Issue was described in https://github.com/WeblateOrg/weblate/issues/13300
> fix(aresource): correctly handle nested escaped quotes

- tests/translate/storage/test_aresource.py
- translate/misc/xml_helpers.py
- translate/storage/aresource.py
Fixes #5464
I'm not really convinced this is a good idea, as this changes output for everybody, so I'd truly like to get some feedback on this change.
@NLLAPPS, @razor313, @johan12345, @TrianguloY, @eighthave, @JustSwiftIt, @nikclayton I'm mentioning people who recently reported issues on Android in this repository or Weblate and might provide valuable feedback here.
> feat(android): include trailing newline in generated XML

- tests/translate/storage/test_aresource.py
This should now cover all what Weblate does.
Fixes #5403
> tests(android): add more CDATA tests

- tests/translate/storage/test_jsonl10n.py
- translate/storage/jsonl10n.py
Avoid rasing confusing TypeError and describe the cause instead.
Fixes https://github.com/WeblateOrg/weblate/issues/13664
> fix(arb): gracefully handle wrong syntax in the file

- translate/storage/jsonl10n.py
The old one was too greedy causing very slow processing of large files.
> fix(json): corrected comment strip regexp

- README.rst
- remove non-working one
- add documentation link
- make the look consistent
> fix: update README badges

- COPYING
- the address was replaced by URL to download the license
- some markup changes
> chore: update GPL text

- .readthedocs.yml
- Makefile
This should make the CI build slightly faster.
> docs: use parallel build

- pyproject.toml
- tests/translate/convert/test_web2py2po.py
- tests/translate/misc/test_multistring.py
- translate/convert/web2py2po.py
This is what web2py uses as well.
> fix(webpy): use ast.literal_eval

- .github/workflows/docs.yml
- .github/workflows/pre-commit.yml
- .github/workflows/setup.yml
- .github/workflows/test.yml
This makes it easier to track what each update changes.
> chore: pin exact action versions

- tests/translate/storage/test_aresource.py
See https://github.com/WeblateOrg/weblate/issues/14214
> tests: add testcase for mixing quotes with XML markup

- tests/translate/storage/test_aresource.py
- translate/storage/aresource.py
- handle quotes across XML elements
- gracefully handle unpaired quotes
Fixes #5543
> feat(android): more robust quotes handling

- translate/storage/fluent.py
Small PR - fixes the error message to include to number of fluent entries
> fix: display number of fluent entries

- translate/storage/xml_extract/unit_tree.py
Split just once as we only need the last part.
Ruff (PLC0207)
> chore(xml): avoid excessive split

- translate/storage/base.py
- translate/storage/properties.py
- add missing type annotations
- directly import quote functions for simplified code
> chore(properties): improve type annotations

- translate/lang/tok.py
Toki Pona (ISO 639-3: `tok`) is a constructed language and small world language.
The settings chosen to ignore the simplecaps and startcaps tests as the language does not use capitalisation for common words, only for proper names, which by its grammar can never show up at the start of the sentence without a common word before it.
> Toki Pona language settings

- tests/translate/storage/test_po.py
> test: add testcase for #5661

- docs/commands/pofilter_tests.rst
- translate/filters/checks.py
> fix: update link to pyenchant

- docs/releases/3.8.1.rst
- tests/translate/convert/test_dtd2po.py
- tests/translate/convert/test_prop2po.py
- tests/translate/filters/test_pofilter.py
- tests/translate/tools/test_pogrep.py
- translate/lang/team.py
- translate/storage/trados.py
- translate/storage/ts.py
Discovered by typos upgrade to v1.37.1 in #5721
> fix: various typos
