README.rst
setup.py
translate/convert/po2resx
translate/convert/po2resx.py
translate/convert/resx2po
translate/convert/resx2po.py
translate/convert/test_po2resx.py
translate/storage/resx.py

Resolving issues found in the review of PR #3242.
Feedback from @dwaynebailey: 
> 1. Missing wrapper scripts for resx2po and po2resx see e.g. translate/convert/ical2po
> 2. Missing copyright headers - we're going to revise these soon anyway but for now how would you like to be credited e.g. SJ Hale, fullname version or some company.
> 3. Missing resx2po and po2resx in setup.py
> 4. Possibly an error in encoding headers in one of the test files.
@dwaynebailey - I think I've addressed all the issues above, please let me know if I've missed (or misunderstood!) anything! 
Re: 2, I'd like to use my full name (Sarah Hale) please :)

Small updates for the new resx2po / po2resx converter

---

docs/developers/styleguide.rst
translate/storage/placeables/parse.py

- Remove the note on arbitrary single vs double quoting, always use double.
- Rename "String quoting" section into "Strings" section
- Move "String formatting" to a subsection of "Strings"

Styleguide: Reorganize string-related guidelines

---

docs/developers/styleguide.rst
docs/formats/base_classes.rst
translate/search/match.py
translate/storage/benchmark.py
translate/storage/dtd.py
translate/storage/mo.py
translate/storage/qm.py

print 'as a statement' does not exist any longer in Python 3.

Removed usage of remaining print-as-a-statement

---

translate/search/indexing/__init__.py
translate/search/indexing/test_indexers.py
translate/storage/_factory_classes.py
translate/storage/placeables/__init__.py
translate/storage/xml_extract/test_xpath_breadcrumb.py

Python 3 does not accept implicit relative imports.
Making those explicit.

Added relative imports where appropriate

---

docs/api/misc.rst
translate/convert/convert.py
translate/convert/idml2po.py
translate/convert/odf2xliff.py
translate/convert/po2idml.py
translate/convert/po2web2py.py
translate/convert/prop2mozfunny.py
translate/convert/xliff2odf.py
translate/misc/optrecurse.py
translate/misc/wStringIO.py
translate/services/tmserver.py
translate/storage/csvl10n.py
translate/storage/dtd.py
translate/storage/fpo.py
translate/storage/ical.py
translate/storage/ini.py
translate/storage/jsonl10n.py
translate/storage/placeables/test_terminology.py
translate/storage/pypo.py
translate/storage/subtitles.py
translate/storage/test_mo.py
translate/tools/test_pocount.py

The cStringIO module is no more in Python 3, and the io module
has been introduced in Python 2.6.

Replaced cStringIO.StringIO by io.BytesIO

---

translate/misc/ourdom.py
translate/misc/wsgiserver/wsgiserver3.py
translate/storage/csvl10n.py
translate/storage/ical.py
translate/storage/lisa.py
translate/storage/poparser.py
translate/storage/poxliff.py
translate/storage/symbian.py
translate/storage/tmx.py
translate/storage/xliff.py

This new 'next' syntax is needed for Python 3 compatibility.

Replaced item.next() by next(item)

---

translate/convert/test_po2ical.py
translate/convert/test_po2ini.py
translate/lang/common.py
translate/lang/el.py
translate/lang/hy.py
translate/storage/placeables/general.py
translate/storage/test_po.py
translate/storage/test_properties.py

Raw unicode strings syntax (e.g. ur'mystring') is not valid syntax on
Python 3.
Read https://www.python.org/dev/peps/pep-0414/#exclusion-of-raw-unicode-literals
This patch uses various techniques to workaround this issue: removing either
the raw or unicode markers when they are not essential, or using unicode_literals
to mimic the Python 3 behavior.

Avoided raw unicode strings for Python 3 compatibility

---

translate/convert/test_po2ts.py
translate/storage/cpo.py
translate/storage/fpo.py
translate/storage/pocommon.py
translate/storage/pypo.py
translate/storage/test_cpo.py
translate/storage/test_po.py
translate/storage/test_pypo.py

PO files can't cope with duplicate messages, so they are removed when parsing
and a warning is logged
Fixes translate/pootle#3564

Removing duplicate messages in PO file parsers

---

translate/misc/optrecurse.py
translate/tools/poconflicts.py
translate/tools/porestructure.py
translate/tools/poterminology.py

`except Exception` is not catching KeyboardInterrupt, so there is no use
examining the exception for it. Only bare excepts are catching it.

Removed unreachable KeyboardInterrupt catching

---

translate/storage/cpo.py

When testing with USECPO=1, this is fixing a bunch of errors from
the error callback function:
TypeError: cannot concatenate 'str' and 'int' objects

Fixed cpo error formatting

---

translate/filters/checks.py
translate/filters/test_checks.py

Exclusion of checks should be easier than this.  But for now do it this way.

Checks: Python braces not needed for LibreOffice

---

translate/filters/checks.py
translate/filters/helpers.py
translate/filters/prefilters.py
translate/misc/optrecurse.py
translate/search/match.py
translate/storage/mo.py
translate/storage/poxliff.py
translate/storage/pypo.py
translate/storage/qph.py
translate/storage/test_base.py
translate/storage/tmdb.py
translate/storage/ts2.py
translate/storage/xliff.py

Several constructs in Python 3 do not return lists any longer, but
iterators instead, like filter(), map(), .keys(), .values(), etc.
When iterating, this is not a problem, but where we need a list,
the iterator has to be consumed in a list.

Transformed iterators to lists when needed

---

translate/convert/test_po2dtd.py
translate/storage/aresource.py
translate/storage/catkeys.py
translate/storage/csvl10n.py
translate/storage/dtd.py
translate/storage/fpo.py
translate/storage/ical.py
translate/storage/ini.py
translate/storage/jsonl10n.py
translate/storage/lisa.py
translate/storage/mo.py
translate/storage/mozilla_lang.py
translate/storage/omegat.py
translate/storage/php.py
translate/storage/properties.py
translate/storage/rc.py
translate/storage/subtitles.py
translate/storage/test_properties.py
translate/storage/tiki.py
translate/storage/txt.py
translate/storage/utx.py
translate/storage/wordfast.py

The leading idea is that the file classes should know about
their encoding for serialization, but not the units.

Made unit classes encoding agnostic

---

translate/lang/el.py
translate/misc/dictutils.py

As recent Python version have hash randomization by default,
we had random failure with Greek test_punctranslate because depending
on the order of the dict, replacement could follow: "?" -> ";" -> "·".

Fixed ordering issue in Greek punctuation conversion

---

translate/storage/pocommon.py

On Python 3 unquote_plus accepts only text (unicode) and returns text.

Made unquote_plus Python 3 compatible

---

translate/storage/statsdb.py
translate/storage/tmdb.py

dbapi2.connect accepts bytestring param on Python 2, but text
param on Python 3.

Provided proper text param for dbapi2.connect

---

translate/storage/base.py

Python 3 doesn't seem to like opening files with the file
class. Let's stick to the classical open().

Reopen file with open instead of a class constructor

---

translate/storage/base.py

As text (unicode) becomes ubuquitous on Python 3, it is easier
to just accept and transform any text content to bytes in parsetring
before feeding parse() with it.

Accept unicode input for parsestring

---

translate/storage/base.py

This is the continuation of deferring serialization to
stores instead of units. Moreover, this makes it compatible
with Python 3.

Output text from TranslationUnit.__str__

---

translate/convert/xliff2po.py

This workaround was introduced for a Pootle use case, and the
PootleFile object it was supposed to support is gone since 2009.
Moreover, the `file` type object is no more on Python 3.

Removed obsolete hack in xliff2po.convertstore

---

translate/misc/wsgiserver/ssl_pyopenssl.py
translate/misc/wsgiserver/wsgiserver2.py
translate/search/indexing/XapianIndexer.py

Even if some files might not be used with Python 3, the
'python -m compileall' command may choke on syntax issues.

Fixed compiling all code on Python 3

---

translate/storage/aresource.py
translate/storage/test_aresource.py

There are locales which Babel doesn't know but are valid and crashing on
these is not nice. The code now falls back to using plurals as for
English.
Signed-off-by: Michal Čihař <michal@cihar.com>

Do not fail on unknown locale

---

docs/releases/dev.rst
translate/storage/jsonl10n.py
translate/storage/test_jsonl10n.py

By default JSON will use a normal dict for objects.  Overridding this
and using OrderedDict means we can maintain order and thus translator
context.
Thanks http://stackoverflow.com/a/6921760/2167584
Fixes #3394

JSON: Use OrderedDict to maintain unit order

---

.travis.yml
setup.py
tests/odf_xliff/test_odf_xliff.py

Looks like difflib.unified_diff doesn't accept bytes any longer.

Added Python 3.5 compatibility in tests

---

translate/misc/optrecurse.py

BytesIO has no reset method.  So simply seek to the start of the file.
Fixes #3419

optrecurse: use .seek(0,0) instead of missing .reset

---

docs/releases/dev.rst
translate/misc/deprecation.py
translate/misc/multistring.py
translate/misc/test_multistring.py

We've hit an issue in Pootle which can only be reproduced with TTK master (https://github.com/translate/pootle/issues/4594). The real cause of this is unclear (@phlax mentioned this is originating somewhere in `Store.update()`), and it seems like coercing `multistring`s with non-ASCII data to unicode fails.
In that sense, I'm not sure whether `multistring` should accept bytes in its constructor or not, however previously this [used to work via the `autoencode` class](https://github.com/translate/pootle/blob/02c993c59fadde9f495934ce0a34b87d523ad5f1/pootle/apps/pootle_store/fields.py#L59-L79) (note the `UTF-8` argument to the constructor) which is now removed in master.
I have added a test and a patch for this, which when creating the object would decode bytes from UTF-8 if that was passed. …

multistring: restore decoding bytes

---

translate/misc/multistring.py
translate/misc/test_multistring.py

At the moment code such as `'%s' % [multistring(u'føø')]` fails: the
representation of `multistring` is used when coercing the list to text, however
there are decoding errors.
This commit adjusts the representation of `multistring`s so that a) coercing
lists containing `multistring`s is fixed, and b) the representation allows to
re-create the original object.
On b), this is what the official docs on `repr()` suggest at
https://docs.python.org/2/library/functions.html#repr:
>  For many types, this function makes an attempt to return a string that would
>  yield an object with the same value when passed to eval(), otherwise the
>  representation is a string enclosed in angle brackets that contains the name
>  of the type of the object together with additional information often
>  including …

multistring: fix list coercion to text

---

translate/misc/multistring.py
translate/misc/test_multistring.py

Previously you were able to do `str in dict_with_plural_multistring_key` and because the str and multistring hashes matched it would find the dict element.
This PR adds a test to demonstrate how ttk behaviour version has changed, and a fix to restore old beviour

Multistring hash (for plurals)

---

translate/storage/aresource.py
translate/storage/test_aresource.py

The format now handles \n and newline equally, so we can remove specific
handling for newlines.
Fixes #3262

Simplify newlines handling

---

docs/formats/index.rst
docs/formats/mozilla_lang.rst
translate/convert/test_po2mozlang.py
translate/storage/mozilla_lang.py
translate/storage/test_mozilla_lang.py

Based on files in the wild the final unit is, like all units, followed
by newlines.

mozlang: last unit is followed by trailing newlines

---

requirements/optional.txt

It seems it fixed some flaws in Python 3 support.

Bump vObject requirement again

---

translate/search/indexing/CommonIndexer.py
translate/search/indexing/XapianIndexer.py
translate/search/indexing/__init__.py

The recent release of Xapian 1.4 offers Python 3 support for Xapian. Since Xapian support has not been available until now, there are parts of the indexer code that have never been tested with Python 3.
The following patch set:
- Fixes the API usage to be compatible with Xapian 1.4; only one small change in the `translate-toolkit` (`_create_query_for_query`) is required as the (unneeded) copy constructor `xapian.Query(query)` is no longer exported. The copy wasn't needed with older Xapian either so this is backwards compatible.
- Fixes the usual little Python 2 to 3 gremlins with dicts, encoding and imports.
These patches are included in the upload of `translate-toolkit` 2.0.0~b5-2 in Debian `experimental` that enables Python 3 support for translate-toolkit and also its xapian indexer. …

Add support for Xapian 1.4 and Python 3

---

tests/cli/data/test_pocount/stderr.txt
tests/cli/data/test_pocount_help/stdout.txt
tests/cli/data/test_pocount_mutually_exclusive/stderr.txt
tests/cli/data/test_pocount_po_file/stdout.txt
tests/cli/test_pocount_po_file.sh
translate/tools/pocount.py

Hello, i see that issue #2162 is still uncompleted for a long time.
I am adding color support with ANSI color code that enabled by default, but can be toggled off with `pocount --no-color`.
Here are some screenshot
Edit: I also change the output text a bit, so I'm altering the test data too.
Edit 2: I'm beginner with testing and travis thing, sorry for the failing build. Will fix it soon.

Add color support for pocount output

---

translate/lang/ro.py
translate/lang/test_ro.py

I took another look at my old pull request and I decided to take a more thorough look at things and create some smaller changes instead. As a first trial, I'd like to add a new filter that does some simple checks for the target strings if the target language is Romanian.

added Romanian checks for obsolete cedilla characters

---

translate/lang/ro.py
translate/lang/test_ro.py

Added more checks for Romanian for "nici un" and "nici o" (a common error).
On top of that, code simplification since reduce logic was flawed for substrings.

Romanian checks: niciun, nicio and pythonic refactoring

---

translate/storage/mozilla_lang.py
translate/storage/test_mozilla_lang.py

.lang: parse MAX_LENGTH into comments

---

tests/cli/data/test_po2txt/one.po
tests/cli/data/test_po2txt/out.txt
tests/cli/data/test_po2txt_threshold/one.po
tests/cli/test_po2txt.sh
tests/cli/test_po2txt_threshold.sh
translate/convert/convert.py

unit objects are not hashable, so use getunitid() instead.
Adds functional tests.
Fixes a py3 bug

Fix --threshold

---

translate/storage/test_ts2.py
translate/storage/ts2.py

this allows you to get/set context for a ts unit only when the unit
is not part of a tsfile
it allows pootle to use ttk to derive the correct `id`, but it doesnt
add the required implementation for ts to work when changing a units
context, or inserting a unit that has had its context set

Add setcontext for ts format

---

translate/storage/test_yaml.py
translate/storage/yaml.py

Using str is not a good idea on Python 2 as it fails on unicode literals.

Fixed parsing of unicode values in YAML lists

---

.travis.yml

IMHO it is way more usable than coveralls you're using right now. One feature that I like is adding coverage as a status to pull requests, both for patch and overall. I see you're using it for Pootle already, so it might be good idea to have it on translate-toolkit as well.
It needs to be enabled on the codecov.io side as well (and granted access to the GitHub project).
I've kept the coveralls integration in place for now, it can be removed later.

Add codecov.io support

---

tests/cli/data/test_po2ts/one.po
tests/cli/data/test_po2ts/out.txt
tests/cli/test_po2ts.sh
translate/convert/po2ts.py
translate/convert/test_po2ts.py

This fixes an issues with po2ts in which we don't encode the output to UTF-8 when required for writing to file.  This was either fallout from Python 3 changes or lack of Unicode testing in po2ts.
@Artoria2e5 the changes to fix your reported issue are just those in f50aace4e62e37bdc9d122f8b59da4d7b7b5bc68 if you want to patch your local installation of Translate Toolkit

Fix po2ts encoding issues

---

translate/storage/aresource.py
translate/storage/test_aresource.py

The original report #3262 was invalid, the format does not work this
way, so this reverts commit a5ffe4c02d0d1b64930baca6512e29665d0d7e42.
Changes:
- \n is the only thing which is parsed as newline
- newline is stored as \n, together with real newline for better readability
See https://github.com/WeblateOrg/weblate/issues/1418 for discussion, most importantly https://github.com/WeblateOrg/weblate/issues/1418#issuecomment-290725588 is statement from original reporter of #3262.

Improve newlines handling in Android

---

translate/storage/resx.py

It seems that resheader.reader and resheader.writer are necessary for
Visual Studio to properly load the file.

Improve resx skeleton

---

translate/convert/po2php.py
translate/convert/test_php2po.py
translate/convert/test_po2php.py
translate/storage/php.py
translate/storage/test_php.py

This PR adds:
- some tests to `TestPhp2PO`;
- allow to use `'app'->'string1'` location instead of `return+array->'app'->'string1'` for the following example:
```php
<?php
return array(
'app' => array(
'string1' => 'Source',
),
);
```
It fixes inconsistence how we define locations with phpfile parser and po2php converter.
It's worth to add test to cover this inconsistence specifically.

Add phpfile tests for strings within array()

---

translate/convert/test_po2prop.py
translate/convert/test_prop2po.py
translate/storage/properties.py
translate/storage/test_properties.py

When the properties file contains only key and lacks value, the
find_delimiter returns None as delimiter and it can be later serialized
as None string into the file. By setting delimiter to empty string, we
keep the file as is.

Improved behavior on corrupted properties files

---

translate/convert/test_po2resx.py
translate/storage/resx.py

There are a few things that currently happen when roundtripping ResX files that are otherwise modified by Visual Studio:
- The XML Declaration switches from double quotes to single quotes and from lower-case to upper-case encoding
- The inline XML Schema is slightly reformatted (mostly spacing, such as before the `/>` of an empty tag)
- The `<data>` element is incorrectly indented (4 spaces instead of 2)
All those make it rather noisy in the VCS, especially when an automated tool such as [Weblate](https://github.com/WeblateOrg/weblate/) does the committing.
This PR attempts to fix the 3rd bullet by updating the `element.tail` depending on whether a `<comment>` tag is present or not.
However, the majority of the changes ended up in getting the tests to work again, because they currently do …

Make ResX indent closer to what .NET Resource files look like after editing with Visual Studio

---

.travis.yml
docs/conf.py

Getext does not seem to be installed automatically on Travis now, but
it's used by tests.

Fix Travis failures (install Gettext and fix pytest docs URL)

---

translate/storage/test_ts2.py
translate/storage/ts2.py

It's not desirable to return None as a location in case the tag is
completely empty.

Handle gracefully empty location tag in QT ts

---

translate/convert/po2idml.py
translate/storage/aresource.py
translate/storage/lisa.py
translate/storage/placeables/lisa.py
translate/storage/poxliff.py
translate/storage/test_xliff.py

The lxml allows defining external entities by default and that can lead
to including content of external files using them. This can be really
problematic for services dealing with user uploaded files such as Pootle
or Weblate.
This is least intrusive fix, but maybe it would be better to use [defusedxml](https://pypi.python.org/pypi/defusedxml) instead of lxml directly.
You can find more information about this kind of vulnerability here: https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Processing

Avoid resolving external entities while parsing XML

---

translate/storage/aresource.py
translate/storage/test_aresource.py

The leading and trailing whitespace is stripped by Android.
See http://tekeye.uk/android/examples/android-string-resources-gotchas

Strip leading and trailing whitespace from Android resources

---

translate/lang/data.py

this prevents languages with dialects from showing as `langname (macrolanguage)`
there are other cases where the part of the name in brackets doesnt refer to a country which we might also want to exclude in this way

Improve country name handling in lang translations

---

translate/filters/checks.py
translate/filters/test_checks.py

Strip out directionality markers before performing the puncspacing test.
Fixes #3635

Checks: remove bidi markers before puncspacing test

---

translate/lang/data.py
translate/lang/test_data.py

Ensure we get 'Taiwan' not 'Taiwan, Province of China'.  Which impacts which translations we'll pick up.

Use common_name for lang/country if available

---

translate/storage/test_xliff.py
translate/storage/xliff.py

currently ttk creates a `unit.getid()` with filename + `\x04` + unitid
but when you addunit with a unitid as above it ignores the filename part and puts all units into a `NoName` filenode
this PR corrects that so that xliff files more closely roundtrip

Correctly set filenode when adding units to xliff store

---

translate/storage/pocommon.py
translate/storage/test_pocommon.py

These really do not have to be escaped in the po file, so keep them as
they are.
The list probably could be extended, but this is what I've spotted while reviewing https://github.com/translate/translate/pull/3673

Avoid escaping some chars in po files

---

translate/convert/test_convert.py
translate/convert/test_po2dtd.py
translate/lang/test_identify.py
translate/misc/test_multistring.py
translate/storage/test_cpo.py
translate/storage/test_html.py
translate/storage/test_pypo.py
translate/storage/test_qm.py
translate/tools/test_pomerge.py

The code is currently pretty inconsistent as pointed out in https://github.com/translate/translate/pull/3696#discussion_r152043518

Cleanup: Consistenly use pytest.raises as context manager

---

translate/storage/base.py

This avoids raising 'DeprecationWarning: use the name attribute' on some
files.

Get only name attribute when it exists

---

translate/storage/pypo.py
translate/storage/test_pypo.py

Setting this to high value can avoid wrapping altogether to mimic --no-wrap from gettext, setting to -1 completely removes line wrapping (including newlines).

pypo: Allow to configure output width

---

.travis.yml
translate/storage/html.py
translate/storage/pypo.py

I think this would be useful to avoid using deprecated interfaces.
Depends on #3711 and #3710

Make DeprecationWarning a failure in tests

---

translate/convert/test_txt2po.py
translate/convert/txt2po.py
translate/storage/txt.py

This adds a flag `--no-segmentation` to txt2po which when specified will cause the whole file to be dumped into a single messages in the PO file.
Fixes  #3698

Add --no-segmentation flag to txt2po

---

translate/storage/test_pypo.py

Note that this currently *is* broken on Windows - if the file has unix newlines, it won't get properly parsed, see https://github.com/translate/translate/issues/3751

pypo: Add tests for parsing files with different newlines

---

translate/storage/test_poheader.py

The Africa/Windhoek TZ is changing; Namibia changes its TZ definitions in 2018
and so this test fails when run after 2018-04-01.
From tzdata Release 2017c - 2017-10-20 14:49:34 -0700:
Namibia will switch from +01 with DST to +02 all year on
2017-09-03 at 02:00.  This affects UT offsets starting 2018-04-01
at 02:00.  (Thanks to Steffen Thorsen.)
This particular test isn't hitting code paths not addressed by other tests
so removing it is simplest.
Closes: https://github.com/translate/translate/issues/3754

Stop testing with changing Africa/Windhoek TZ

---

Makefile

This hides real error in some cases making it harder to figure out real
cause of build failure.
Right now the build is failing because of missing virtaal documentation
which is linked through intersphinx, see
https://github.com/translate/virtaal/issues/3277

Avoid running sphinx in parallel

---

translate/storage/pypo.py
translate/storage/test_pypo.py

When the file is open in binary mode (what usually is), the implicit
iterator works only on platform native newlines. For example that means
that parser would fail to parse po files with unix newlines on Windows.
On the other side the splitlines uses universal newlines handling
correctly any newlines on any platform.
Fixes #3751

Use splitlines instead of implicit iterating on file

---

docs/installation.rst

The > does not have to be quoted on Windows.
Fixes #3707

Fix installation instructions for Windows

---

.travis.yml

These are failing and just wasting build resources.
AFAIK nobody is working on making this work, they can be easily added back once somebody does.

RFC: Remove USECPO=1 tests

---

translate/storage/jsonl10n.py
translate/storage/test_jsonl10n.py

This can be used for example to force different indentation or keys
sorting.

JSON: Add support for customizing json.dumps args

---

translate/storage/pypo.py
translate/storage/test_pypo.py

Gettext seems to prefer wrap lines after /, while translate-toolkit doesn't
This is visible especially when having URLs in the string, example can be seen here:
```diff
--- a/weblate/langdata/locale/cs/LC_MESSAGES/django.po
+++ b/weblate/langdata/locale/cs/LC_MESSAGES/django.po
@@ -8,11 +8,11 @@ msgid ""
msgstr ""
"Project-Id-Version: Weblate 2.20\n"
"Report-Msgid-Bugs-To: weblate@lists.cihar.com\n"
-"POT-Creation-Date: 2018-02-23 10:36+0000\n"
+"POT-Creation-Date: 2018-03-05 15:49+0000\n"
"PO-Revision-Date: 2018-02-23 11:35+0000\n"
"Last-Translator: Pavel Borecki <@gmail.com>\n"
-"Language-Team: Czech "
-"<https://hosted.weblate.org/projects/weblate/languages/cs/>\n"
+"Language-Team: Czech <https://hosted.weblate.org/projects/weblate/languages/"
+"cs/>\n"
"Language: cs\n"
"MIME-Version: …
```

pypo: Consitent wrapping on / with Gettext

---

translate/storage/test_yaml.py
translate/storage/yaml.py

We convert both to string on loading and store them as string.
Fixes #3619

YAML: Consistent handling of int and bool

---

translate/convert/test_po2tmx.py
translate/filters/test_pofilter.py
translate/storage/test_tmx.py
translate/storage/tmx.py

The file can be created by anything using Translate Toolkit, so
mentioning po2tmx might be confusing and makes people think there is
some po file existing for the data.

TMX: Avoid mentioning po2tmx in creation tool

---

translate/storage/php.py
translate/storage/test_php.py

Consistently use lexer to extract name as is used in the original file
instead of relying on parser to return the exact way.

PHP: Improve handling of unit name

---

translate/convert/ini2po.py
translate/convert/po2ini.py
translate/storage/ini.py

There is no official support in iniparse upstream, but for example
Debian ships patched iniparse version to work with Python 3.

INI: Fix ini for Python 3

---

translate/storage/resx.py

`strings` is only written to, but never read anywhere. Seemed to be in there since ResX was first committed, but has no effect whatsoever. Unless I missed some pythonic side-effect that isn't obvious.

resx: remove unused variable

---

translate/convert/test_po2resx.py
translate/storage/resx.py
translate/storage/test_resx.py

Yet another change to make ResX play nicer with VCS.
Before this, adding new units to a file (ie. when a source resx has the entry, but the target resx does not) would put the new `<data>` entry where the closing `</root>` was (not indented at all), and the new `</root>` indented as if it was `<data>`.
```diff
--- a/Resources.de.resx
+++ b/Resources.de.resx
@@ -126,4 +126,7 @@
<data name="ExistingEntry" xml:space="preserve">
<value>Bestehender Eintrag</value>
</data>
-</root>
+<data name="NewEntry" xml:space="preserve">
+    <value>Neuer Eintrag</value>
+  </data>
+  </root>
```
After the change, only the newly added `<data>` is part of the diff (as it should be), leaving the surrounding tags alone.
```diff
--- a/Resources.de.resx
+++ b/Resources.de.resx
@@ -126,4 +126,7 @@
<data …
```

resx: Properly indent new entries

---

translate/storage/resx.py

The settarget is deprecated since 2.3.1, but it might still be used and
should behave properly. Without method here, the one from LISAunit gets
called and it behaves completely differently.

RESX: Add settarget compatibily

---

translate/storage/properties.py
translate/storage/test_properties.py

- generic fix of missing `\` escaping in properties test
- fixed storing changed value in Joomla, see https://github.com/WeblateOrg/weblate/issues/1716

Joomla fixes

---

translate/storage/pypo.py
translate/storage/test_po.py
translate/storage/test_pypo.py

In case \r is included in comment text and whole file is having \n
newlines, the univerzal newlines approach breaks lines on wrong
locations, while gettext handles this just fine.
This addresses regression introduced by https://github.com/translate/translate/pull/3760, see https://github.com/WeblateOrg/weblate/issues/1986#issuecomment-386704921

pypo: Fix parsing of files with mixed newlines

---

translate/storage/jsonl10n.py
translate/storage/test_jsonl10n.py

We need to use OrderedDict to ensure the ordering of values is kept
while saving.

JSON: Preserve ordering of nested values

---

translate/storage/properties.py
translate/storage/test_properties.py

This fixes: https://github.com/translate/translate/issues/3824
There is a bug when reading multiline OS X strings.
In the file: storage/properties.py , the stringsfile and stringsutf8file classes derive from the properties class.
It looks like .properties files can have multiline strings but using a backslashes \ (or that is what I understood looking at the code), but OS X string files do not require that. Instead, to check for the end of the string the last character, that should be a ';'.
Could not make the tests in the master branch pass, and did not understand how to create a new test to raise the issue (in an initial commit) and then commit the fix. So, I know that this is not a good enough PR, but if you try to import the OS X strings file that I attach, you will find it fails. …

fix import OS X strings file

---

translate/storage/aresource.py
translate/storage/test_aresource.py

It was added to the format:
https://developer.android.com/guide/topics/resources/string-resource
Fixes https://github.com/WeblateOrg/weblate/issues/2206

Android: Correctly handle escaping of question mark

---

translate/storage/jsonl10n.py
translate/storage/test_jsonl10n.py

There is no message attribute on exception in Python 3.

JSON: Fix exception handling in Python 3

---

.travis.yml
requirements/dev.txt
translate/misc/test_deprecation.py

Python 3.7 is now out and so it's time to add that to the test matrix. Some jiggling is required to express the test matrix in a sensible fashion to get Python 3.7.
There's also a new version of pytest out, and with either pytest 3.9 or 3.10, the way the `deprecated` decorator was tested broke; a second commit to fix that.

Add python 3.7 to testing matrix and fix failing tests with pytest 3.10

---

translate/storage/aresource.py

The plurals are already properly sorted in the data module, there is no
need to sort them again.

Android: Remove not needed code

---

translate/storage/placeables/general.py
translate/storage/placeables/test_general.py

Mapping keys for Python can be any string, currently podebug is rewriting values such as:
```
msgid "Camp story - %(object.name)s"
msgstr "Ƈȧḿƥ şŧǿřẏ - %(ǿƀĵḗƈŧ.ƞȧḿḗ)ş"
```
This PR should allow any character inside the parentheses. I've also added some tests which should hopefully cover most of the common PythonFormattingPlaceable cases.
Closes #3705

Python formatting fix

---

.travis.yml

- current lxml no longer supports it making installation fail
- 3.3 has reached end of life on 2017-09-29

Remove Python 3.3 from test matrix

---

translate/storage/trados.py

Needed to hide TradosSoup from Sphinx autodoc module as it makes no
sense to include Soup documentation (especially as it fails to build
using Sphinx).

Trados: list all public memebers

---

translate/storage/pypo.py
translate/storage/test_pypo.py

Run detection starting at "msgid" string. This should be better way to
detect actual newlines used to detect the strings.
See https://github.com/WeblateOrg/weblate/issues/2519

Gettext: Improve finding out newline format for a file

---

requirements/optional.txt
translate/convert/test_yaml2po.py
translate/storage/test_yaml.py
translate/storage/yaml.py

- This allows us to remove majority of custom code around preserving
order of keys
- It supports YAML 1.2 which supports yes/no as keys (see #3695)

YAML: Switch to ruamel.yaml

---

translate/misc/dictutils.py

It was deprecated in dict years ago and translate-toolkit doesn't use it
(see #3451), so there is no good reason to implement it.

Misc: Remove has_key implementation

---

translate/storage/pypo.py
translate/storage/test_pypo.py

Such file is not conforming with how Gettext tools behave, but
apparently some editors create such files.
Fixes #1640

Gettext: Strip UTF-8 BOM from input

---

requirements/recommended.txt

It seems to be causing random segfaults on both Travis CI and AppVeyor.
Fixes #3873

Avoid using lxml 4.3.1

---

translate/misc/test_xml_helpers.py
translate/misc/xml_helpers.py
translate/storage/aresource.py
translate/storage/resx.py
translate/storage/test_aresource.py
translate/storage/test_resx.py
translate/storage/test_xliff.py
translate/storage/ts2.py
translate/storage/xliff.py

This introduces generic XML formatting code based on #3670 and uses that in Android, Resx (what simplifies it's code) and Xliff (what fixes #3424).

XML indentation for Android, Resx and Xliff

---

translate/storage/csvl10n.py
translate/storage/test_csvl10n.py

Changed default quoting to csv.QUOTE_ALL from csv.QUOTE_NONNUMERIC. The
problem with csv.QUOTE_NONNUMERIC is that it tries to convert all non
quoted stringst to float leading to exceptions when parsing the files
without quoted strings:
ValueError("could not convert string to float: 'ID'")
The root cause is that sniffer is not able to detect a delimiter, but
this seems to be fixed in Python 3.7.

CSV: Make default dialect more flexible

---

translate/misc/xml_helpers.py
translate/storage/test_ts2.py

The toplevel tags were wrongly indented in some cases.

Misc: Fix indentation of toplevel tags

---

translate/convert/test_csv2po.py
translate/storage/csvl10n.py
translate/storage/test_csvl10n.py

Really rely on sniffer here, otherwise we might strip too much (the
escape char in CSV is meant only for quotes, otherwise the parser just
strips the escape char).
Fixes #3246

CSV: Avoid hardcoding escape char

---

translate/storage/aresource.py
translate/storage/base.py
translate/storage/cpo.py
translate/storage/csvl10n.py
translate/storage/fpo.py
translate/storage/omegat.py
translate/storage/php.py
translate/storage/properties.py
translate/storage/pypo.py
translate/storage/qph.py
translate/storage/rc.py
translate/storage/tbx.py
translate/storage/tmx.py
translate/storage/utx.py
translate/storage/xliff.py

Similarly like with addnote and getnotes, this now accepts origin on all
storages, even when most of them do ignore it.

Storage: consistent API for removenotes

---

translate/storage/subtitles.py

It is set in SubtitleFile._parse, but the attribute should be already
present.

Subtitles: Initialize duration in __init__

---

requirements/dev.txt

The pytest version is frozen, so shuld be all extensions to ensure they
are compatible.
This should fix current test failures.

Tests: Freeze pytest extension versions

---

translate/storage/base.py
translate/storage/properties.py

I'm not sure with this change, but to me it looks weird that *all* formats accept empty files through `parsefile` or `parsestring` even when those are not syntactically valid (eg. XML or JSON based formats).
The code in question was introduced in https://github.com/translate/translate/commit/9141370e95ac5ced702aa1b503d1cfbb96051c6a where it was ported from some formats.

Change empty file handling

---

translate/convert/test_po2resx.py
translate/storage/resx.py
translate/storage/test_resx.py

Make formatting consistent with Visual Studio output:
- use double quotes in XML declaration
- remove trailing end line
- add space before empty tags closing
Addresses https://github.com/WeblateOrg/weblate/issues/2807

RESX: Consistent formatting with Visual Studio

---

translate/storage/csvl10n.py

There is no good reason constructing the StringIO twice.

CSV: Share StringIO for parsing and detection

---

tests/cli/data/test_po2ts/out.txt
translate/convert/po2ts.py
translate/convert/test_po2ts.py
translate/storage/test_ts2.py
translate/storage/ts2.py

Fixes issue where po2ts would remove consecutive linebreaks in source and translated strings.  Added tests.
(I'm not sure why the blank-line removal code was there in the first place; I traced it back as far as 9836716 (12 years ago) and it isn't documented.  Removing it doesn't break any tests.)

Stop removing blank lines in .ts files

---

translate/storage/pypo.py
translate/storage/test_pypo.py

This repeatedly added blank lines to the output, see https://github.com/WeblateOrg/weblate/issues/2954

pypo: Fix serializing long msgidcomments

---

translate/storage/pypo.py
translate/storage/test_pypo.py

Addresses situation when typecomments contain more complex things than just those few defined by gettext.

pypo: Fix handing typecomments with non word chars

---

translate/misc/xml_helpers.py
translate/storage/aresource.py
translate/storage/test_aresource.py

Properly parse, indent and store XML entities.
Fixes #3907

Android: Fix XML enttites handling

---

translate/storage/poparser.py
translate/storage/test_pypo.py

The pypo parser happily parsed any file as containing no unit - it just
stopped on first line and did not report any error. Now the ValueError
is raised in case it can not parse the whole file.

pypo: raise erorr on invalid file content

---

translate/storage/properties.py
translate/storage/test_properties.py

Without this the files in utf-16 encoding get saved with escaped unicode chars, see https://github.com/WeblateOrg/weblate/issues/3099

properties: Fix saving utf-16 java files

---

translate/misc/xml_helpers.py
translate/storage/aresource.py
translate/storage/test_aresource.py

The whitespace can have meaning there even if xml:whitespace is not set.

Android: Fix indentation of markup in translation

---

translate/storage/aresource.py
translate/storage/test_aresource.py

Generating template from the file failed to remove plurals and other elements leading to generating messed up output as can be seen here: https://github.com/Etar-Group/Etar-Calendar/pull/580/commits/75c18f1e3223b3c1d7b520e88635f58abb4f24e1

Android: Fix setting plural with markup

---

requirements/recommended.txt
translate/storage/aresource.py
translate/storage/test_aresource.py

The new unit can contain XML entities not present in current
document.
Discovered in https://github.com/WeblateOrg/weblate/issues/3177

Android: Clone document declaration when adding unit

---

translate/convert/po2web2py.py
translate/convert/test_po2web2py.py
translate/convert/test_web2py2po.py
translate/convert/web2py2po.py

web2py includes `@markmin\x01` in the unit's source string when the string uses web2py's markmin formatting.  However, it does not copy over to the translation.  This PR updates the converter to reflect this same behavior, allowing a smoother experience.

po <-> web2py: don't copy "@markmin" string

---

translate/convert/prop2po.py

The getnotes() returns string, there is no reason in joining it
char by char.

prop2po: Remove not needed join

---

translate/convert/test_prop2po.py
translate/storage/properties.py
translate/storage/test_properties.py

The units with comment only are problematic as they can not be
identified - the getid returns just empty string for all of them. This
makes it hard to process them. Concatenating such comments makes it also
behave consistent with other storages.
Fixes #3928

Properties: Avoid creating comment only units

---

translate/storage/pypo.py
translate/storage/test_poheader.py

The empty line inside comments are usually intentional, so avoid dropping them
on round trip.
Issue was brought up by @fujiwarat at https://github.com/WeblateOrg/weblate/issues/3376

pypo: Avoid stripping empty lines from comments

---

translate/storage/mo.py
translate/storage/test_mo.py

It was mistakenly kept as bytes, making later string join on that crash.

mo: Fix parsing context

---

translate/storage/aresource.py
translate/storage/test_aresource.py

When new target is plain text, the any possible child elements were
kept leaving some mess in the string.

aresource: Fix setting target and removing markup

---

translate/storage/aresource.py
translate/storage/test_aresource.py

We need to remove all children before using (not only elements, but also comments).

aresource: Fix setting rich content with comments

---

translate/storage/test_mo.py

Fixes testing on s390 and others.

Msgfmt to use the same byte order as pocompile

---

requirements/optional.txt
translate/storage/test_yaml.py

The 0.16.6 release fixed handling of empty keys, while the test relied
on previous broken behavior.
Fixes #3949

yaml: Adjust test to recent ruamel.yaml

---

translate/storage/test_ts2.py
translate/storage/ts2.py

This way all callers can rely on it being present avoiding
errors when operating on None.
Addresses crash described in https://github.com/WeblateOrg/weblate/issues/3603#issuecomment-599529168

ts2: create translation element in _gettargetnode

---

translate/storage/jsonl10n.py
translate/storage/test_jsonl10n.py

Such files are violating RFC, but it suggests that parses should be able
to skip this, see https://tools.ietf.org/html/rfc7159#section-8.1

json: allow usage of BOM in JSON files

---

docs/formats/catkeys.rst
translate/convert/pot2po.py
translate/storage/catkeys.py
translate/storage/test_catkeys.py

The catkeys format now has support for fingerprint calculation.
This means that if the tools change the contents of the file (like
remove or change strings), the header will now be correct and the file
will be parseable on Haiku.
When merging with pot2po, it will use the template header to determine
the language of the output format.

Catkeys: merge header and fingerprint

---

setup.py

Fixes #3958
This time without tests and other changes, see https://github.com/translate/translate/pull/3959 and https://github.com/translate/translate/issues/3958

Setup: Import setuptools before py2exe

---

translate/storage/aresource.py
translate/storage/test_aresource.py

In some Android builds, the plurals which do not have "others" are not handled
properly and cause application to crash (android.content.res.Resources$NotFoundException).
Adding "others" as a copy of "many" should address this.

Android: Workaround broken plural handling

---

docs/formats/yaml.rst
translate/storage/test_yaml.py
translate/storage/yaml.py

- use parsed file when saving
- this preserves comments and syntax from the original file
- avoid using merged keys, we do not want to duplicate them
Fixes #3695

yaml: Utilize round trip features of ruamel.yaml

---

translate/storage/test_yaml.py
translate/storage/yaml.py

When the parsed document is empty, the parser returns just None and further processing fails. This change ensures there is always valid root.

yaml: Fixed adding units to empty document

---

.github/workflows/osx.yml

Something has changed in the brew and link --force no longer works for
gettext. Adding it to PATH should adddress this.

Fix osx tests by adding gettext to path

---

.github/workflows/win.yml

It seems that updating system package is not allowed.

ci: fixed pip upgrade on Windows

---

.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/linux.yml
.github/workflows/osx.yml
.github/workflows/setup.yml
.github/workflows/win.yml

This prevents the double build for DependaBot PRs, so they only run when it opens a PR, and not when it creates a branch

chore: Don't build dependabot branches

---

.github/workflows/win.yml

3.5 is currently failing for python-Levenshtein https://github.com/nschonni/translate/runs/639706148?check_suite_focus=true#step:6:131 so still not added to matrix

chore: expand Windows matrix

---

.github/workflows/osx.yml

Now matches the Linux coverage, minus the minimal build

chore: Add 3.6 to macOS matrix

---

CREDITS
docs/commands/html2po.rst
docs/formats/html.rst
translate/convert/test_html2po.py
translate/convert/test_po2html.py
translate/storage/html.py
translate/storage/test_html.py

A makeover of the HTML parsing to fix issues #3768 (html2po incorrectly strips html),
#3416 (incorrect sub-strings substitution), and a few other issues for which there are no bug reports. Unit tests have been added to expose those cases.
The new parsing algorithm does not use any regex-based parsing on top of the HTML parser. Instead, it puts the content inside localisable HTML elements on a queue which is processed when the end of the localisable content is reached. This means that one can use the DOM of the translatable content when extracting localisable content, which makes it easier to handle edge cases.
Also includes a fix for #3884 (translate language version in <html lang="en">). This fix is better than the PR I submitted earlier, because it does not extract the lang tag from …

[html2po] multiple bug fixes, parsing makeover

---

translate/storage/factory.py
translate/storage/test_factory.py

This is useful to inject existing store as output for convertors.
I've originally made similar change only for one convertor in https://github.com/translate/translate/pull/4022 (now removed), but it turns out to be more generic pattern, so I think placing it into the factory makes more sense.

Factory: Accept store as parameter to getobject

---

translate/convert/po2prop.py
translate/convert/test_po2prop.py

properties: Fix round trip of empty values without delimiter

---

translate/storage/pypo.py
translate/storage/test_po.py
translate/storage/test_pypo.py

The line wrapping in Getext is more complex and the regexp based
splitter is always an approximation of that, but this makes it behave
more similar to what the original implementation does.
The PO wrapper is now a class instead of monkey patched instance of
generic wrapper.
Fixes https://github.com/WeblateOrg/weblate/issues/3852

pypo: Bring line wrapping closer to gettext

---

translate/storage/ini.py

This is how other formats behave and it is easier to handle than
catching error in constructor.

ini: Raise error on module import

---

translate/misc/deprecation.py
translate/misc/multistring.py

This was supposed to be dropped in translate-toolkit 2.0, but it stayed
there a bit longer.
Fixes #3681

multistring: Remove deprecated behavior

---

README.rst
requirements/recommended.txt
requirements/required.txt
translate/storage/dtd.py
translate/storage/lisa.py

Lot of code uses it without catching the import error and I think it is
used often enough to be required.
Fixes https://github.com/translate/translate/issues/4004
Alternative approach could be to remove now empty requirements.txt, see https://github.com/translate/translate/pull/4002

requirements: make lxml required

---

translate/storage/aresource.py
translate/storage/test_aresource.py

This was introduced by #4049 and went unnoticed because it was not covered by tests.

aresource: Fix unicode literals parsing

---

translate/convert/test_csv2po.py
translate/storage/test_php.py
translate/storage/test_po.py
translate/storage/test_trados.py

Some test methods were duplicate leading to ignoring one of them.

tests: Resolve duplicate method names

---

translate/convert/odf2xliff.py
translate/convert/oo2xliff.py
translate/convert/po2xliff.py
translate/convert/po2yaml.py
translate/misc/optrecurse.py

The dictionaries had duplicate keys, which are silently ignored. Changed
optrecurse to accept iterable and store the formats in tuple instead.

convert: Fix conversion to multiple formats

---

translate/lang/factory.py
translate/storage/benchmark.py
translate/storage/factory.py
translate/storage/versioncontrol/__init__.py

- User functools.lru_cache to cache imports
- Switch to import_module for doing imports
- Remove own cache implementation in versioncontrol
Based on suggestions in #3492

Use LRU cache for imports

---

translate/misc/quote.py
translate/storage/properties.py
translate/storage/test_properties.py

* Informations about XWiki Translation Format are available there: https://dev.xwiki.org/xwiki/bin/view/Community/XWiki%20Translations%20Formats/
* Add new xwiki dialect to handle special escape of simple quotes
* Improve propunit to allow handling missing translations serialized
in comments
* Add xwiki unit that uses xwiki dialect and a specific comment prefix
for missing translations
* Add xwiki file that uses xwiki units

Support XWiki Formats

---

translate/storage/aresource.py
translate/storage/test_aresource.py

Using quotes does not work well with HTML markup, so another escaping is
needed. Using unicode quote seems to be safest in this case.

Android: Fix escaping double space with HTML

---

translate/storage/aresource.py
translate/storage/test_aresource.py

Additional whitespace would be included in the string due to inserting
newline to XML for better readability. Android itself seems to strip
this as well.

Android: Fix round trip of strings with newlines

---

translate/storage/properties.py
translate/storage/test_properties.py

* Fix indent on the copyright section.
* Always put language information, and retrieve properly source
language from XML.

fix: XWiki Format: Avoid wrong indent and missing language.

---

translate/storage/properties.py
translate/storage/test_properties.py

- Fix extracting language for XWiki Full Page format
- Use language or default language
- Ensure to output properly the unit when serializing by using source
or translation
- Ensure to serialize the locale in root node.

fix: Final fixes for XWiki Format

---

translate/storage/test_mo.py

Calls to external tools such as `msgfmt` and `pocompile` need to be checked to ensure that they succeeded. If they were to fail for any reason, then the test will fail at a later line, but for the wrong reason.

Ensure external tools ran successfully in tests

---

translate/storage/base.py
translate/storage/jsonl10n.py
translate/storage/yaml.py

The code is doing pretty much same thing and both implementations were covering different corner cases. This PR merges both implementations and uses single code for both formats.

Share serializer code for YAML and JSON

---

translate/storage/base.py
translate/storage/jsonl10n.py
translate/storage/test_jsonl10n.py
translate/storage/test_yaml.py
translate/storage/yaml.py

YAML and JSON storages now preserve structure on round trip even when it contains strings used in the unit IDs. The structure is kept in separate object and is used when saving.
Fixes #3819
Fixes #3857
Fixes #3541
Supersedes https://github.com/translate/translate/pull/3835
Built on top of https://github.com/translate/translate/pull/4090, only last commit is relevant here.

storage: Preserve structured IDs on round trip

---

translate/convert/po2dtd.py
translate/storage/base.py
translate/storage/cpo.py
translate/storage/dtd.py
translate/storage/pocommon.py
translate/storage/test_dtd.py

- initialize index attributes in __init__
- require index for find as we scan all units anyway
- fix super __init__ invocation in cpo
- make isblank and index usage consistent with other formats in dtd

storage: Consolidate index usage

---

translate/storage/yaml.py

It needs to have root node as language, without that the subsequent serialize
calls operate on invalid data.

yaml: Fix generating blank document

---

translate/storage/base.py
translate/storage/cpo.py
translate/storage/flatxml.py
translate/storage/lisa.py
translate/storage/test_base.py
translate/storage/test_cpo.py
translate/storage/test_properties.py
translate/storage/test_qm.py
translate/storage/yaml.py

storage: Add support for removing units
This is a useful feature when managing monolingual files and complements the addunit API.
Built on top of https://github.com/translate/translate/pull/4108

storage: Add support for removing units

---

translate/storage/csvl10n.py
translate/storage/test_csvl10n.py

This allows to keep the decision on sample length on the application, giving it control
on accurancy / speed / memory consumption tradeoff.
See https://github.com/WeblateOrg/weblate/issues/2805

csv: Allow to specify sample length for CSV sniffer

---

translate/storage/base.py
translate/storage/jsonl10n.py
translate/storage/test_base.py
translate/storage/test_po.py
translate/storage/yaml.py

Without that, the monolingual units with same translation are treated
equal. Specifically, all untranslated monolingual units are treated
equal.

Storage: Include id while comparing units

---

.github/workflows/setup.yml
docs/developers/releasing.rst
requirements/dev.txt

This avoids need to manually install those at release and CI time and
makes the release process more controlled as both versions are pinned.

deps: Include twine and virtualenv in dev deps

---

.github/workflows/linux.yml
.github/workflows/osx.yml
README.rst
requirements/dev.txt
setup.py

Python 3.5 reached the end of its life on September 13th, 2020. pip 21.0
will drop support for Python 3.5 in January 2021 and others will
probably follow.

Deps: Increase minimal Python version to 3.6

---

.pre-commit-config.yaml
requirements/dev.txt
setup.cfg
setup.py

That makes it easier to track version which should be used.

lint: Use native isort to have just one dependency on that

---

translate/storage/aresource.py
translate/storage/test_aresource.py

Share the code for XML and non-XML code paths so that both remove existing childs.
Related issue to https://github.com/translate/translate/issues/4135

android: Fix setting escaped content for XML

---

translate/storage/subtitles.py
translate/storage/test_subtitles.py

- Fix Unit class behavior to be consistent with other formats and
provide default values which do nor crash the serialization
- Mark most of the tests a expected failure as most of the formats are
actually broken in current aeidon, see #4155

Subtitles: Add basic tests for the formats

---

translate/storage/jsonl10n.py
translate/storage/test_jsonl10n.py

This is a regression introduced by #4091 as that makes the flat JSON
file expand the unit keys.
Fixes https://github.com/WeblateOrg/weblate/issues/4779

json: Fix handling of newly created units for flat JSON format

---

docs/commands/html2po.rst
docs/commands/option_multifile.rst
translate/convert/html2po.py
translate/convert/test_html2po.py
translate/misc/optrecurse.py
translate/storage/html.py

Sometimes it can be more convenient to work with a single pot/po file for an entire web site, or part of a web site, instead of one per html file. For example, this is a workflow familiar to authors of WordPress plugins. This PR adds that option to html2po.
The function is invoked through the "multifile" command-line option, an option which is provided by some of the other converters for similar purposes. It might be better to create a new option for it. Please let me know what you think.
The PR also removes an obsolete and non-functional option to include untagged content from html2po.

Html2po: option for single file output

---

translate/storage/test_xliff.py
translate/storage/xliff.py

Setting it only on first one will produce mixed language xliff,
what is usually not desired.
Fixes https://github.com/WeblateOrg/weblate/issues/4945

xliff: set xliff language on all file nodes

---

translate/storage/xliff.py

It provides massive overhead when parsing xliff files as it is called for every unit.

xliff: Skip switchfile logic if not needed

---

translate/storage/rc.py
translate/storage/test_rc.py

The chardet does not reliably detect utf-8, so check it's result by
looking at the code_page #pragma.
Fixes #4190

rc: Use code_page #pragma to detect encoding

---

translate/storage/xliff.py

In many cases the ID is replaced just after adding unit, so it
is not reasonable to spend much time on calculating it.

xliff: generate IDs based on total number of units

---

translate/convert/po2ts.py
translate/filters/checks.py
translate/filters/test_checks.py
translate/lang/data.py
translate/lang/ngram.py
translate/misc/multistring.py
translate/storage/aresource.py
translate/storage/cpo.py
translate/storage/dtd.py
translate/storage/flatxml.py
translate/storage/fpo.py
translate/storage/lisa.py
translate/storage/oo.py
translate/storage/poxliff.py
translate/storage/properties.py
translate/storage/pypo.py
translate/storage/resx.py
translate/storage/statistics.py
translate/storage/statsdb.py
translate/storage/tbx.py
translate/storage/test_base.py
translate/storage/test_pypo.py
translate/storage/test_xliff.py
translate/storage/tmdb.py
translate/storage/tmx.py
translate/storage/ts2.py
translate/storage/xliff.py
translate/storage/xml_extract/extract.py

This code is there from Python 2, where it was reasonable to expect that
the parameters can be both unicode or str. In Python 3, it is safe to
assume that it is always a str and bytes should be properly handled at
caller.

misc: Remove not necessary conversion from bytes

---

translate/storage/test_csvl10n.py

The location is parsed correctly, when one expects it to parse as a
context, the headers have to be provided.
Fixes #3356

csv: Complete test for location/context parsing

---

translate/storage/wordfast.py

* Avoid sharding default dict to avoid modifying it.
* Add mising attribute to parser.

wordfast: Fix header processing

---

docs/commands/html2po.rst
docs/commands/index.rst
translate/convert/po2html.py
translate/convert/test_po2html.py
translate/misc/optrecurse.py

Sometimes it can be more convenient to work with a single pot/po file for an entire web site, or part of a web site, instead of one per html file. For example, this is a workflow familiar to authors of WordPress plugins. The option to extract translatable content from an entire web site into a single po file was added to html2po in #4179. This pull request adds the inverse operation to po2html.
The function is activated when a single PO file is given as input, and a directory of HTML files given as template. Instead of iterating over the input files, the converter will iterate over the template files and produce one output file per template file.
The pr also includes a little cleanup of the documentation: the entries on the Converters page are sorted alphabetically to make them easier to …

Po2html: option for single PO file input

---

translate/storage/poparser.py
translate/storage/test_cpo.py
translate/storage/test_po.py

The invalid syntax of comments could lead to infinite recurision in case
none of the parsers matches on them. Raise a ValueError in that case.
Fixes #4232

po: Raise ValueError on invalid syntax

---

translate/storage/rc.py
translate/storage/test_rc.py

The chardet is really bad in detecting these and having nul char inside
the string is a good indication for this case.

rc: Fixed parsing of UCS-2 RC files

---

translate/storage/test_cpo.py
translate/storage/test_pypo.py

Those were iso-8859-1, but Python reads the files as utf-8 now.

tests: Properly encode unicode strings

---

translate/convert/test_po2dtd.py
translate/storage/cpo.py
translate/storage/poparser.py
translate/storage/test_cpo.py
translate/storage/test_po.py

It is not possible to raise an exception from ctype callback this way.
Store the exception in (thread local) variable and raise it when leaving the call.
Discovered when working on https://github.com/translate/translate/pull/4235, see https://stackoverflow.com/a/42443453/225718 for more details.
This causes tests to fail, I'd like to get feedback first whether such change looks okay.

cpo: Fix raising exceptions from ctypes

---

translate/storage/base.py
translate/storage/test_jsonl10n.py

This avoids problems when changing the file structure and new units
being not compatible with old ones.

json: Gracefully migrate lists to hashes

---

translate/storage/aresource.py
translate/storage/lisa.py
translate/storage/resx.py
translate/storage/ts2.py
translate/storage/xliff.py

Reuse same serialize method in all indenting storages. This reduces code
duplication and makes it easy to introduce indenting to other storages.

lisa: Share XML indentation code

---

translate/storage/properties.py
translate/storage/test_properties.py

* Ensure that when performing a change in a XWikiPageProperties source
file the XML is not modified. Fixes #4265

fix: do not modify XWikiPageProperties source file

---

translate/storage/properties.py
translate/storage/test_properties.py

The GWT format is supposed to use Java MessageFormat formatting which
doubles single quotes, see http://www.gwtproject.org/doc/latest/tutorial/i18n.html

properties: Handle single quote escaping in GWT

---

translate/storage/test_yaml.py
translate/storage/yaml.py

We can represent these since introduction of structured ids, so there is
no reston to block them.

yaml: Do not fail on numeric keys

---

translate/tools/poterminology.py

The [ lacked escaping causing FutureWarning.
Fixes #4282

poterminology: Fix regex escaping

---

translate/storage/aresource.py
translate/storage/test_aresource.py

The root element can have a namespace and that broke the string
replacements. Instead of detecting the content, force the XML to include
proper closing tag (instead of self-closing one). This way the text
replacement is safe and does not break on additional attributes defined
on the root element.
Fixes https://github.com/WeblateOrg/weblate/discussions/5657

Android: Improve XML handling

---

translate/storage/properties.py
translate/storage/test_properties.py

Call encode only when changing and avoid it on serialization. This
heavily reduces serialization time for big files. Also now all properties
dialect behave consistently with decode/encode methods.

Properties: consolidate encode/decode

---

translate/storage/properties.py
translate/storage/test_properties.py

It prevented proper handling of the escape sequences.

Properties: Add forgotten super invocation in Joomla

---

translate/storage/test_ts2.py
translate/storage/ts2.py

This is how Qt tools do that.
Fixes https://github.com/WeblateOrg/weblate/issues/5917

ts2: Consistent using of XML entity for non-breakable space

---

README.rst
requirements/required.txt

To address  Cross-Site Scripting in lxml (CVE-2021-28957)

deps: Increase lxml dependency

---

translate/storage/poparser.py
translate/storage/test_po.py

The original gettext parser fails on these and translate-toolkit
should be consistent with it.

po: Fail on syntactically invalid PO files

---

translate/convert/convert.py
translate/convert/test_po2dtd.py
translate/filters/test_checks.py
translate/search/test_match.py
translate/storage/test_dtd.py

There are small typos in:
- translate/convert/convert.py
- translate/convert/test_po2dtd.py
- translate/filters/test_checks.py
- translate/search/test_match.py
- translate/storage/test_dtd.py
Fixes:
- Should read `preserve` rather than `preseve`.
- Should read `placeholder` rather than `placeholds`.
- Should read `individual` rather than `invidividual`.
- Should read `gracefully` rather than `graacefully`.
- Should read `differently` rather than `differerntly`.
Closes #4382

docs: Fix a few typos

---

translate/storage/placeables/strelem.py

Python 3 can print unicode directly.

placeables: Remove not needed encode

---

.github/workflows/pre-commit.yml
.pre-commit-config.yaml
requirements/dev.txt

This makes it more self-contained and allows to use pre-commit.ci service.

ci: Use native pre-commit modules

---

translate/storage/stringsdict.py
translate/storage/test_stringsdict.py

#3238 
This implements Stringsdict as defined by Apple. While it can be used for regular strings, it's recommended to only use this format to store plurals.
Apple deviates from the CLDR Language Plural Rules standard in the following ways:
* All languages support the 'zero' category. This implementation prepends the 'zero' category in every language that doesn't define it already.
* The 'other' category is always used when a category has a missing string, including in languages that doesn't have 'other' defined in the list of tags. This is currently unsupported by this implementation, and the 'other' string is not preserved when parsing a file in a language that doesn't define it.

stringsdict: Add support for stringsdict storage

---

translate/storage/jsonl10n.py
translate/storage/test_jsonl10n.py

If not handled here, the json complains on passing None which does
not really tell what went wrong.

json: Handle crash when can not detect encoding

---

translate/convert/po2rc.py
translate/convert/test_po2rc.py

The parser operates based on \n, but the RC file is typically using \r\n.

rc: Avoid duplicating \r in po2rc

---

translate/storage/html.py
translate/storage/test_html.py

This makes the parser preserve whitespace in `<pre>`, fixes #3265.
While looking into the code, I've made some other minor cleanups.

html parser improvements

---

.gitmodules

It should have been done years ago, but nobody noticed that. It is now being switched off by GitHub, see https://github.blog/2021-09-01-improving-git-protocol-security-github/

chore: Update submodule URL to https

---

translate/convert/po2rc.py
translate/convert/test_po2rc.py

When outputting a STRINGTABLE:
- Construct msgid correctly when it's multiline
- If a translation isn't available, output the continuation lines indented (not separated by ',')
- If a translation is available, it's output on a single line (since we don't know where to break lines)
Fixes #4115

Better handling of multiline stringtable translations in po2rc

---

translate/storage/pypo.py

This code is broken for years without anybody noticing, so
it should be safe to remove.

pypo: Remove unused, untested and broken pounit.parse

---

.github/workflows/docs.yml
.github/workflows/linux.yml
.github/workflows/osx.yml
.github/workflows/pre-commit.yml
.github/workflows/setup.yml
.github/workflows/win.yml

These end up in the pull requests, so there is no good reason to run
everything twice.

ci: Avoid running CI on pushes to deepsource branches

---

translate/storage/base.py
translate/storage/xliff.py

- it is not useed anywhere in the translate-toolkit
- the variant with filename has weird side effect of changing id_index
- the only external user seems Pootle and it does not use filename

storage: Remove filename arg from getids method

---

translate/convert/test_po2dtd.py
translate/convert/test_po2oo.py
translate/convert/test_pot2po.py
translate/storage/test_base.py
translate/storage/test_oo.py
translate/tools/test_pretranslate.py

pytest captures them since the 3.1 release.

tests: Avoid manually handling warnings

---

translate/misc/xml_helpers.py
translate/storage/test_xliff.py
translate/storage/xliff.py

- add tests that clearing works
- move the code to the xml helpers
- document why clear() is not a choice (and caused unnoticed regression
in bb7d23bb09ba3c8d0d557821d3c8b8662dabc05f)

xliff: Refactor element clear

---

.github/workflows/linux.yml
.github/workflows/osx.yml
.github/workflows/win.yml
README.rst
setup.py

Maybe you want to keep it for a bit, but it hit EOL at the end of December https://devguide.python.org/devcycle/#end-of-life-branches

feat: drop Python 3.6

---

.github/workflows/docs.yml
.github/workflows/linux.yml
.github/workflows/osx.yml
.github/workflows/pre-commit.yml
.github/workflows/setup.yml
.github/workflows/win.yml

Pointin to v2 will reduce some Dependabot noise, till there is a v3 release

chore: unpin core GitHub Actions

---

requirements/optional.txt
translate/storage/base.py
translate/storage/test_csvl10n.py

This is better maintained and more reliable detection.
This avoids issues with chardet mistakenly reporting utf-8 content as    windows-1252, see https://github.com/chardet/chardet/issues/185

formats: Switch to charset-normalizer from chardet

---

translate/convert/po2rc.py
translate/convert/test_po2rc.py

The code would either crash on undefined variable or re-use its content
from the previous loop.

po2rc: Fix handling identical source strings with different ID

---

.github/workflows/docs.yml
.github/workflows/linux.yml
.github/workflows/osx.yml
.github/workflows/pre-commit.yml
.github/workflows/setup.yml
.github/workflows/win.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

translate/storage/jsonl10n.py
translate/storage/test_jsonl10n.py

This currently can not be represented well and breaks when adding new
units.

json: Avoid parsing root node

---

translate/storage/pypo.py

Sum lengths instead of building possibly huge string just to calculate
its length.

pypo: Improve _msgstrlen performance for plurals

---

translate/storage/csvl10n.py
translate/storage/test_csvl10n.py

It is unreliable in many cases and users might want to avoid it.

csv: Allow to override encoding detection

---

.github/workflows/win.yml

pip on Windows can be upgraded only via `python -m pip` to avoid having
pip binary open while it is upgrading.

ci: Fix pip upgrade

---

docs/conf.py

The %s was missing the in the label.

docs: Fix sphinx.ext.extlink configuration

---

tests/cli/data/test_rc2po/one.rc
translate/storage/rc.py
translate/storage/test_rc.py

Fix how identifiers are found after a concatenated string in MENU and
DIALOG resources.
After extract_test() has consumed one or more adjacent quoted string
tokens to concatenate, the following token is the identifier.
This fixes an oversight in 2c581f31.

rc: Fix how identifiers are found after concatenated string

---

translate/convert/po2rc.py
translate/convert/test_po2rc.py

This is the same change as  #4481, for dialog controls rather than stringtable entries.

Better handling of translations of concatenated string in dialog controls in po2rc

---

translate/storage/rc.py
translate/storage/test_rc.py

We want to use this only in case there is more than one constants being
combined.
Fixes #4642

rc: Fixed parsing of combined constants

---

translate/storage/aresource.py
translate/storage/test_aresource.py

- order plurals in defined order instead of relying on the ordering in
the file
- add blank string in place of missing plurals
This should allow graceful migration to new plural rules used by recent
Android versions, see https://github.com/WeblateOrg/weblate/issues/7888

android: Correctly order plurals

---

setup.cfg

It introduced check for inline comments what fails on
listing non breakable space in the escape map.

lint: Update ignore for flake 5.x

---

translate/storage/rc.py
translate/storage/test_rc.py

When using tools like Resource Hacker to extract an RC file from a compiled binary EXE, resource identifiers are not `#define`d because the name cannot be reproduced from the binary. Instead, the numeric IDs are used directly. Furthermore, in the case of string tables, there is a comma after the resource ID. Running `rc2po` on such files produces an empty result.
Simply allow numeric IDs, and an optional comma after `id_control`. Everything else seems to fall into place nicely.
A comma after the resource ID seems to be a documented feature for string tables: https://docs.microsoft.com/en-us/windows/win32/menurc/stringtable-resource#examples
Whether this causes any issues with other resource types, I cannot say. Tests all pass, however.
Converting such PO files back to RC was not tested, …

Allow numeric resource IDs in RC files

---

translate/storage/rc.py

Make the code more consistent (and faster) by using f-strings.

rc: Utilize f-strings instead of concatenation

---

docs/commands/option_rewrite.rst
docs/commands/podebug.rst
translate/tools/podebug.py
translate/tools/test_podebug.py

Looking for a tool to test my translation I found (remind) podebug with rewriter was a really good tool.
But It was missing an option to spot strings that have not been integrated yet.
I tried with Chef and Flipped, but it was still not enough obvious.
That's why I created the NSA rewriters 
Based on flipped it keeps variables but obfuscates all alphanumeric characters with a black square 
Perhaps it can serve the community, so I made this PR...

Add new rewriter to spot easily what is not part of the translation file 

---

.gitignore
MANIFEST.in

The setuptools_scm does not automatically include submodules, so we have to do that manually for now.
See https://github.com/pypa/setuptools_scm/issues/206
Fixes #4744

dist: Include doc theme in dist manually

---

translate/storage/base.py
translate/storage/test_jsonl10n.py

- Improve detection of the root node to look at actual parsed unitis instead of examining strings ids. This makes the behavior consistent with behavior possibly overridden UnitId subclasses.
- Extend JSON tests to cover more complex adding behavior.
- Include unitid parsing in the DictUnit API to make it reusable.

json: Improve handling of mixed indices

---

translate/lang/el.py
translate/misc/optrecurse.py
translate/storage/base.py
translate/storage/jsonl10n.py
translate/storage/poheader.py
translate/storage/properties.py
translate/storage/stringsdict.py
translate/storage/test_poheader.py
translate/storage/yaml.py

Since Python 3.7 the dict is guaranteed to be ordered as well.

chore: Remove OrderedDict usage

---

translate/storage/jsonl10n.py
translate/storage/test_jsonl10n.py

Sometimes number is intended to be a string in the JSON file and it is reasonable to translate it.

json: Allow overwriting integer with a string

---

translate/misc/xml_helpers.py
translate/storage/lisa.py
translate/storage/test_xliff.py

- ability to override the XML format for XLIFF files
- self-closing tag is set to true by default to prevent conflict with current implementation
- capability will be defer to Weblate as XLIFF Addon like JSON Format (https://docs.weblate.org/en/latest/admin/addons.html#customize-json-output)
- always generate XML declaration in translate-toolkit for consistency
Co-authored-by: Michal Čihař <michal@cihar.com>

feat(lisa): avoid xml self-closing tags

---

translate/storage/jsonl10n.py
translate/storage/test_jsonl10n.py

The random identifier was not overwritten in this case, causing the files having keys like 0x15986331a172306b instead of the actual value.

json: Fix setid behavior for plural JSON units

---

.github/workflows/docs.yml
.github/workflows/linux.yml
.github/workflows/setup.yml

This seems to help with flaky azure mirror used in GitHub CI.
See https://github.com/actions/runner-images/issues/675

ci: Add retries to apt-get

---

translate/storage/base.py
translate/storage/jsonl10n.py
translate/storage/stringsdict.py
translate/storage/test_jsonl10n.py
translate/storage/yaml.py

Otherwise we might be unnecessarily parsing the string again.

dictunit: sed id and parsed id at once

---

translate/storage/stringsdict.py
translate/storage/test_stringsdict.py

This is caused by setid not updateing _unitid (what is desired). The caller needs to call get_unitid prior that.

stringsdict: Fix crash on adding new string

---

translate/storage/jsonl10n.py
translate/storage/test_jsonl10n.py

- v3 stores with _0 suffix in the one plural case
- v4 parses missing plurals correctly (keeps the string positions)

i18next: Improve plural handling

---

docs/formats/json.rst
translate/storage/jsonl10n.py
translate/storage/test_jsonl10n.py

go-i18n v2 supports other data-serialization format (TOML, YAML) with the same structure but I don't know if a mutualization is possible, nor how to do it. But if desirable I'm willing to try with some advices.

json: Add support for go-i18n v2

---

.github/workflows/linux.yml

The update was not actually called due to mismatched quotes.

ci: Fix apt-get invocation

---

translate/storage/jsonl10n.py
translate/storage/test_jsonl10n.py

While trying to implement go-i18n v2 format handling in weblate I saw there was a bug when unit has plurals without a description
I've also simplified the code by relying as much as possible on parent classes

 json: Fix go-i18n v2 unit format on plurals without description

---

translate/storage/poxliff.py
translate/storage/test_poxliff.py

The emebdded unit returns None and passing it to multistring makes it "None" string.

poxliff: Avoid using "None" as string when plural is not translated

---

translate/storage/fluent.py
translate/storage/test_fluent.py

We refactor the parsing and serializing of FluentFiles with a number of
improvements:
+ Fluent Term's keep a prefix "-" id so they can be better identified as  Terms, rather than Messages.
+ Fluent Terms and Messages expose all of their Attributes within a single FluentUnit in a fluent-ish syntax.
+ Multi-line values are now properly handled. In particular, the indent has been removed from the FluentUnit's source.
+ We no longer rely on methods from fluent.syntax sub-modlues that are not part of its public API (serialize_pattern, serialize_placeable, and FluentParser.maybe_get_pattern).
+ We throw ValueErrors if the FluentFile's FluentUnits do not serialize to valid fluent, with improved messaging (see issue https://github.com/translate/translate/issues/4448).
+ No longer include all …

Refactor Fluent parsing and serializing

---

translate/storage/aresource.py
translate/storage/test_aresource.py

PR to fix single whitespace not preserved (#4884)
Includes three new tests to check single whitespace in no-quote, single-quote and full-quote.
A single space on android is not treated differently than multispace, the logic to replace/collapse multiple strings should be the same, as opposed to the source code comment.
About the modified test (test_parse_quoted_newlines)
The input string on android:
when displayed on a textview:
and fetched
returns
Which makes sense, because the '\n' are always converted to linebreaks, and the actual linebreaks are only converter while inside a quoted part, which we are.
Fixes #4884

aresource: fix single whitespace

---

.github/workflows/linux.yml
.github/workflows/osx.yml
.github/workflows/win.yml
.pre-commit-config.yaml
README.rst
requirements/test.txt
setup.cfg
translate/tools/_test_utils.py
translate/tools/pocount.py
translate/tools/test_junitmsgfmt.py
translate/tools/test_pocount.py

Python 3.7 security support ends in 1 month and 1 week, and snapshot testing (syrupy) requires at least 3.8 to work, let's drop it from CI, and then start using snapshot testing instead of the old shell-based tests.

feat: Drop python 3.7

---

translate/storage/rc.py

Use simple string replace instead. This also makes the code more readable due to removed additional escaping for re.

rc: Avoid excessive use of regular expressions

---

translate/convert/test_po2rc.py
translate/storage/rc.py

This preserves a whitespace inside

rc: Make comment a single token

---

Makefile

- This makes the Makefile match CI pipeline
- Avoids failure on DeprecationWarning in third-party code
Fixes #4950

makefile: Avoid failing on DeprecationWarning

---

translate/storage/fluent.py
translate/storage/test_fluent.py

Follows from https://github.com/translate/translate/pull/4822
We do some general fixing up of the fluent code, then we add two methods to the FluentUnit that can be used in weblate:
- get_syntax_error: To extract a syntax error in the unit's source without needing to serialize the FluentFile.
- get_parts: To extract all the individual fluent-relevant parts of the unit's source, including its attributes and its variants. This will help weblate split a single source with multiple attributes and [select expressions](https://projectfluent.org/fluent/guide/selectors.html) into simple individual strings, which can then be checked.

Fluent: add some API for use in weblate

---

translate/convert/test_ts2po.py
translate/convert/ts2po.py

`ts2po` crashes if the first context name is empty. For example, in these files:
- https://raw.githubusercontent.com/MythTV/mythtv/master/mythtv/i18n/mythfrontend_ca.ts
- https://raw.githubusercontent.com/MythTV/mythtv/master/mythtv/i18n/mythfrontend_es.ts
```
> ts2po mythfrontend_ca.ts
processing 1 files...
ts2po.py: WARNING: Error processing: input mythfrontend_ca.ts, output None, template None: cannot access local variable 'messagenum' where it is not associated with a value
[###########################################] 100%
```
The PR skips the unit if the context is empty, rather than crash. Another approach could be setting a default context and initializing `messagenum = 0`, but I understand the context should not be empty in normal circumstances (as it is automatically generated)

fix(ts2po): do not crash and skip unit if the context is empty

---

translate/storage/test_xliff.py
translate/storage/xliff.py

Hello. A bit of background on why I'm proposing this change.
In commit 9061cac1db35a98f2196c14546a456b98ce0b15f, the method _xliffunit.getlocations_ changed its return type from a Python list to a string.
Consider that xliffunit._getlocations_ inherits from class lisa.LISAunit which inherits from class base.TranslationUnit in which _getlocations_ is defined as:
```
def getlocations():
...
return []
```
3 reasons why I'm proposing this change: consistency with base class, consistency with the rest of inhered classes which use a list and for consistency in how we expose the API.

getlocations should return a list instead of string

---

translate/convert/po2rc.py
translate/convert/test_po2rc.py
translate/storage/rc.py

Currently, the rc file converters convert top-level language statements like this:
```
LANGUAGE LANG_ENGLISH, SUBLANG_ENGLISH_US
STRINGTABLE
BEGIN
// ...
END
```
but not block-level ones like this:
```
STRINGTABLE
LANGUAGE LANG_ENGLISH, SUBLANG_ENGLISH_US
BEGIN
// ...
END
```
This PR adds basic support for block-level language statements so that they are converted in the same way as top-level ones are. There’s still no support for more complex scenarios though, e.g. multiple different languages in the same file.
This is my first time working with pyparsing. If there’s a better way to handle this, please let me know.

Convert block-level language statements in rc files

---

.github/FUNDING.yml

Nearly all maintenance on translate-toolkit is currently done by me, so I think it is reasonable to add sponsorship links to Weblate.

Add GitHub sponsors configuration

---

tests/translate/storage/test_pypo.py
translate/storage/poheader.py

The addded header was not respecting parsed newline character and produced mixed newline files when PO was not using \n.

pypo: fix newlines in added header

---

tests/translate/storage/test_aresource.py
translate/storage/aresource.py

- use str.maketrans for more effective string replacements
- escape ? only at the beginning of the string (fixes #5064)

android: improve string escaping

---

translate/misc/optrecurse.py

This avoids leaking file descriptors in the tests and makes sure the content is written at the end of conversion.
Fixes #5071

optrecurse: properly close opened files

---

translate/tools/junitmsgfmt.py

Parsing relies on English output, so avoid failing when other locales are configured.
While revisiting this code, simplify it to use subprocess.run.

junitmsgfmt: reset locales on msgfmt invocation

---

pyproject.toml
tests/odf_xliff/test_odf_xliff.py

The tests are supposed to be executed with module installed now.

tests: Avoid fiddling with sys.path

---

pyproject.toml
translate/convert/accesskey.py

The else non-break loop is never executed, while it was intended to trigger when none label was found so far.

accesskey: fixed fallback path

---

pyproject.toml
translate/storage/placeables/strelem.py

encode() defaults to utf-8 in Python 3.

chore: sync default encoding with Python

---

tests/translate/storage/test_ini.py
translate/storage/ini.py

These are typically valid INI keys, this iniparse behavior seems weird.
Other iniparse consumers seem to do this as well (for example crudini).
Fixes https://github.com/WeblateOrg/weblate/issues/10561

ini: do not treat rem as a comment start

---

tests/translate/storage/test_pypo.py
translate/storage/pypo.py

This ensures that newly added unit is using storage configured line wrapping.
Fixes https://github.com/WeblateOrg/weblate/issues/10392

pypo: update line wrapping on adding unit

---

tests/translate/storage/test_jsonl10n.py
translate/storage/base.py

This is a regression in 2a9c3253a9e013d34ccf1a07984730f9cfff25f4.

storage: fix parsing blank unit id

---

tests/translate/convert/test_po2resx.py
tests/translate/storage/test_resx.py
translate/storage/lisa.py
translate/storage/resx.py

This makes the output consistent with native tooling.
Fixes #5119

resx: Use Windows newlines

---

tests/translate/convert/test_prop2po.py
tests/translate/storage/test_properties.py
translate/storage/properties.py

Make notes behave consistently with other formats - getnotes returns them without formatting and addnote will ensure that the generated file is valid.
Fixes #5121

properties: consolidate notes handling

---

tests/translate/storage/test_aresource.py
translate/storage/aresource.py

Preserve CDATA in round-trip and expose that to translators.
Fixes #4320

android: gracefully handle CDATA content

---

docs/formats/android.rst
tests/translate/storage/test_aresource.py
translate/storage/aresource.py

It only differs in <plural> tag being used.
Fixes #5144

aresource: Add MOKO resources support

---

translate/lang/data.py

Using a copy can easily make it outdated with the primary definition.
Fixes https://github.com/WeblateOrg/weblate/issues/10670

lang: Use up-to-date data for aliased language codes

---

translate/storage/ts2.py

lupdate encodes all unicode whitespace as XML entities, so be consistent with it.

ts2: make special whitespace output compatible with lupdate

---

tests/translate/storage/test_properties.py
translate/storage/properties.py

It performs better and makes the code more readable than chaining replace() calls.

properties: utilize str.maketrans for replacements

---

translate/storage/flatxml.py
translate/storage/lisa.py

The code does not work with None, so there is no reason to make it default.

chore: do not provide default value for required argument

---

translate/storage/lisa.py

- use ternary operator
- remove not needed intermediate variable

lisa: serialize code cleanup

---

tests/translate/storage/test_xliff.py

Generate 120MB file and test the parser on it. This failed to work on older lxml versions, but seems to be just fine on 5.0.0.
Fixes #4302

xliff: test parsing of huge xliff file

---

tests/translate/storage/test_jsonl10n.py
translate/storage/jsonl10n.py

- avoid parsing them as keys
- use UnitId to preserve types in round-trip
Fixes #4867

gotext: preserve unit IDs as stored in the JSON files

---

README.rst
docs/commands/sub2po.rst
docs/formats/subtitles.rst
tests/translate/convert/test_po2sub.py
translate/storage/subtitles.py

Aiedon is available for years and gaupol uses it to parse subtitles, so there is no reason to import from gaupol anymore.

subtitles: drop gaupol module support

---

tests/translate/storage/test_xliff.py

- verify that missing tag removes newlines
- setting target does add xml:space
- parsing it again keeps newlines
Added to cover https://github.com/WeblateOrg/weblate/issues/10811

xliff: test xml:space handling

---

tests/translate/storage/test_xliff.py
translate/storage/xliff.py

There is no reason to differentiate plain and rich targets here, both can contain significant whitespace.
Fixes https://github.com/WeblateOrg/weblate/issues/10811

xliff: preserve whitespace for rich target as well

---

tests/translate/convert/test_json2po.py
translate/storage/pypo.py

Hello,
This make json2po avoids multiple msgctxt in the resulting PO file.
The cause was in the duplicate removal phase; the location of the first occurrence, among other two or more PO entries with the same keys, was added after the third time and later.
Close #4394.
This also adds a minimal example case as follows.
If we have the JSON source:
```json
{
"a": {
"x": "X"
},
"b": {
"x": "X"
},
"c": {
"x": "X"
}
}
```
... then json2po produced PO content whose `.a.x`'s msgctxt was `".a.x\n.a.x"` (with `pypo.py`, not specifying `USECPO=2` or `USECPO=1`), not `".a.x"`:
```po
#: .a.x
msgctxt ".a.x"
".a.x"
msgid "X"
msgstr ""
#: .b.x
msgctxt ".b.x"
msgid "X"
msgstr ""
#: .c.x
msgctxt ".c.x"
msgid "X"
msgstr ""
```
Thank you,
gemmaro.

pypo: avoid adding extra msgctxt if there are 3 or more same msgids

---

tests/translate/storage/test_jsonl10n.py
translate/storage/jsonl10n.py

Due to internal use of i18next-v4 translation files with nonstandard key separators, I've prepared the patch that allows for handling such use cases as flat json files, while preserving handling of plurals. This PR will be followed by  similar PRs to Weblate.
I've added changes to I18Next-V4 tests in order to reduce number of copy-pasted tests.
Have a great day!
Michał Karol

Add support for i18next-v4 json files with different selectors via flat key handling

---

tests/translate/storage/test_pypo.py
translate/storage/pypo.py

- strip actual length of the newline instead of hardcoding one character
- avoid duplicite generating of comments from different scopes
- avoid string concatenation

pypo: fixed DOS newline handling in getnotes()

---

docs/commands/csv2po.rst
translate/convert/csv2po.py
translate/convert/po2csv.py

While context ("msgctxt") parsing was supported for `csv2po`/`po2csv`, it wasn't mentioned in the command line documentation.

doc: add context to csv2po/po2csv CLI reference

---

tests/translate/storage/test_pypo.py
translate/storage/pypo.py

New instance can have wrapper None, so this case should be handled as needed rewrapping.

po: improve rewrapping when adding unit

---

tests/translate/storage/test_properties.py
translate/storage/properties.py

* Ensure to clean up node after performing operation on the XML
* Fix existing tests
See: https://github.com/WeblateOrg/weblate/issues/11896

Fix added spaces in XWikiPageProperties format XML output

---

requirements/required.txt
tests/translate/storage/test_po.py
translate/storage/pypo.py

This covers more use-cases than simple builtin cjklen which focused on CJK letters only.
Issue #5251

fix(pypo): use wcwidth for calculating unicode string width

---

translate/storage/pypo.py

Storing previous position is cheaper than testing prensency in a possibly long list.

fix(pypo): avoid repeatedly scanning escaping list

---

tests/translate/storage/test_yaml.py
translate/storage/yaml.py

When the element is not a dictionary, this is not something we can gracefully parse.

fix(yaml): avoid crash on invalid Ruby YAML files

---

tests/translate/storage/test_aresource.py
translate/storage/aresource.py

The tail can make the processing invalid and we do not need it.

fix(aresource): avoid using tail when extracting inner markup

---

translate/storage/base.py

Returning None here is invalid, this makes it compliant what __eq__ does.

fix(storage): return usable value from __hash__

---

.github/dependabot.yml
.github/workflows/docs.yml
.github/workflows/setup.yml
.gitmodules
.readthedocs.yml
MANIFEST.in
Makefile
docs/conf.py
requirements/dist.txt
requirements/docs.txt

- switch to Furo theme instead of using own one (fixes #5336)
- add copy button to code samples
- add opengraph previews to all pages
- update for upcoming readthedocs.org changes (see https://about.readthedocs.com/blog/2024/07/addons-by-default/)
- dropped all submodule logic as the only submodule is now gone
- avoid redirects in intersphinx caused by trailing slash
- use separate requirements for docs
- add libgettext to doc build for cpo docs

docs: modernize documentation build

---

tests/translate/storage/test_aresource.py
translate/storage/aresource.py

These translate into whitespace in the end and while it is typically invisible (space at the end of text), it can cause issues in some situations.
This is a kind of breaking change because it changes translate-toolkit output.
Fixes https://github.com/WeblateOrg/weblate/issues/12559

fix(android): avoid visible newlines when storing string

---

Makefile

We no longer ship built documentation, so this is no longer needed

chore(build): decouple documentation from build

---

requirements/optional.txt

- avoid using yanked versions
- avoid using versions incompatible with Python 3

deps: bump minimal deps

---

docs/conf.py

This avoids unnecessary warning.

chore(docs): mock Levenshtein import

---

.github/workflows/docs.yml
.readthedocs.yml

Apparently apt_packages is not applied when using commands.

fix(docs): bring back libgettextpo0 to readthedocs

---

tests/translate/storage/test_aresource.py
translate/storage/aresource.py

- drop newline flattening (actual newline followed by \n was parsed just as \n, but Android includes whitespace instead of the actual newline)
- stricten detection of XML context to not miss CDATA sections (these are not included in length or childred of lxml element), see #5374
- leading/trailing whitespace is now stripped for XML context elements

fix(android): make strings parsing more compliant with Android

---

.github/workflows/pre-commit.yml
pyproject.toml

This makes it much more friendly for an user.

chore(lint): use ruff github formatter only at GitHub

---

pyproject.toml
translate/convert/ini2po.py
translate/convert/odf2xliff.py
translate/convert/po2ini.py
translate/filters/checks.py
translate/filters/pofilter.py
translate/lang/identify.py
translate/lang/ngram.py
translate/lang/team.py
translate/search/lshtein.py
translate/storage/mo.py
translate/storage/qm.py

- turn on ruff T201 rule to make sure no print() is used in storage code
- annotate valid print() usage
- turn some print usage into return (these are unused functions)

chore: annotate print() usage

---

pyproject.toml
translate/filters/checks.py
translate/tools/podebug.py

The lambda definition does not bind variables, so these can have unexpected outcome in some situations.

chore: avoid unsafe lambda usage

---

tests/translate/misc/test_multistring.py
tests/translate/storage/test_properties.py
translate/misc/multistring.py
translate/storage/cpo.py
translate/storage/jsonl10n.py
translate/storage/qm.py

- do not implement __cmp__ which is no longer used in Python 3
- simplify some implementation details
- validate multistring strings when constructing
- remove confusing aliases from tests

chore: improve multistring implementation

---

tests/translate/storage/test_aresource.py
translate/storage/aresource.py

We only should strip insignificant XML space here.

fix(android): avoid stripping escaped whitespace from the string

---

tests/translate/storage/test_aresource.py
translate/storage/aresource.py

Avoid manually manipulating with inner XML elements when setting rich content. This allows to keep things like CDATA which are not exposed as childer in lxml.
Fixes #5374

fix(android): inject whole XML element to keep CDATA

---

tests/translate/storage/test_mo.py
translate/storage/mo.py

The #5392 uncovered a bug in charset parsing from MO file - it was never parsed before becase bytes were compared to string. Now we properly decode the charset so that it can be properly used.

fix(mo): fixed parsing

---

translate/storage/jsonl10n.py

When using ArbFiles, we stumbled across the same case in PR https://github.com/WeblateOrg/weblate/issues/4779. See PR https://github.com/WeblateOrg/weblate/issues/13037
To solve this, I tried to adapt PR #4161 to Arb files in the hope that it solves the actual problem
My Python is not that good so someone should definitely look carefully at the change to make sure I didn't mess up.
Would be cool if someone could help me with the TestCases as I have no idea how this works here :D

Also Fix #4161 on ArbFiles

---

translate/storage/jsonl10n.py

This produces easier to understand errors than str object has no attribute get

fix: add type validation to WebExtension parsing

---

tests/translate/convert/test_convert.py
tests/translate/convert/test_po2rc.py
translate/convert/po2rc.py

Allow po2rc output encoding to be specified with the '--charset-output' option, defaulting to automatically choosing cp1252 if possible, otherwise utf-16-le, as before.

Allow po2rc output encoding to be specified

---

translate/misc/progressbar.py

The round function returns integer when invoked without a ndigits arg.

chore: remove not needed int conversion

---

tests/translate/storage/test_aresource.py
translate/storage/aresource.py

This makes \u behavior consistent with otheru unknown escape sequences.

fix(aresource): swallow invalid u escapes same as we do with others

---

tests/translate/storage/test_aresource.py
translate/storage/aresource.py

This behavior is not not specified in the documentation, but Android apparently removes such double quotes (see
https://github.com/WeblateOrg/weblate/issues/13437).
The behavior implemented by us:
- opening quote without a closing quote will treat the string as quoted
- closing quote without an opening quote will be just ignored
Such a quote will be removed on round-trip as it is syntactically invalid.

fix(android): gracefully handle unparied double quotes

---

tests/translate/storage/test_jsonl10n.py
translate/storage/jsonl10n.py

I noticed on Weblate that WebExtension JSON keys are pulled apart. I don't believe this is supported in Chrome or Firefox. This PR uses flat unit ids instead.

Use flat structure for Webextension JSON files

---

tests/translate/storage/test_jsonl10n.py
translate/storage/jsonl10n.py

These are parsed from a single dictionary, so these should not be parsed as possible keys but used intact.
Fixes https://github.com/WeblateOrg/weblate/issues/13037

fix(json): do not attempt to parse fixed keys

---

tests/translate/storage/test_jsonl10n.py
translate/storage/jsonl10n.py

Currently the go-i18n-v2 is being serialized with nested structures, for example the following:
```json
{
"repo.pulls.merged_title_desc": {
"one": "слит %[1]d коммит из <code>%[2]s</code> в <code>%[3]s</code> %[4]s",
"many": "слито %[1]d коммит(ов) из <code>%[2]s</code> в <code>%[3]s</code> %[4]s"
},
"repo.pulls.title_desc": {
"one": "хочет влить %[1]d коммит из <code>%[2]s</code> в <code id=\"%[4]s\">%[3]s</code>",
"many": "хочет влить %[1]d коммит(ов) из <code>%[2]s</code> в <code id=\"%[4]s\">%[3]s</code>"
},
}
```
Will be serialized to the following by translate:
```json
{
"repo": {
"pulls": {
"merged_title_desc": {
"one": "слит %[1]d коммит из <code>%[2]s</code> в <code>%[3]s</code> %[4]s",
"many": "слито %[1]d коммит(ов) из <code>%[2]s</code> в <code>%[3]s</code> %[4]s"
}, …
```

json: output go-i18n-v2 as a flat json

---

tests/translate/storage/test_aresource.py
translate/storage/aresource.py

These are stripped and can cause later when processing the string as it can become blank after removing escape sequences.

fix(android): gracefully handle invalid escape sequences

---

tests/translate/storage/test_jsonl10n.py
translate/storage/base.py
translate/storage/jsonl10n.py

These need to avoid parsing unitid upon parsing key.
See #5471

fix(json): better handle non-nested formats

---

tests/translate/storage/test_aresource.py
translate/storage/aresource.py

This is non-conforming string, so chose simpler approach to just leave the quote as it is instead of trying to detect if it is actually extra quote or escaped one.
Fixes https://github.com/WeblateOrg/weblate/issues/13655

fix(android): avoid stripping possible extra closing quote

---

tests/translate/storage/test_yaml.py
translate/storage/yaml.py

We can not use them as None as that makes us later serialize as "None" string.
See https://github.com/WeblateOrg/weblate/discussions/13441

fix(yaml): gracefully handle blank plural values

---

tests/translate/storage/test_jsonl10n.py

This does not seem to cause any issues now, but reportedly it did at some point in Weblate, see https://github.com/WeblateOrg/weblate/issues/13664

tests: add test for colon in ARB file

---

tests/translate/storage/test_subtitles.py
translate/storage/subtitles.py

This is how subtitles are rendered, so make sure the strings are in the right order and not in the order they have been added to the file.

feat(subtitles): automatically sort subtitle files on saving

---

tests/translate/storage/test_jsonl10n.py
translate/storage/jsonl10n.py

The format is allowed to contain (only) // style comments. Strip these while parsing. This will make them being discarded on round trip.
Fixes #3811
Fixes https://github.com/WeblateOrg/weblate/issues/2043

feat(json): strip comments from webextension

---

tests/translate/storage/test_csvl10n.py
translate/storage/csvl10n.py

When encoding is automatically detected to non utf-8 and serialization fails, the encoding is changed to utf-8. This covers frequent situations when the file is not utf-8 but is edited to contain utf-8 strings.

feat(csv): automatically upgrade encoding to utf-8 on save

---

LICENSES

It is no longer useful since there is just one license.

chore: drop LICENSES

---

.github/workflows/test.yml

This forces any documentation pull request to override branch protection.

chore(ci): avoid ignoring workflows for doc paths

---

tests/translate/storage/test_jsonl10n.py
translate/storage/base.py

We need to drop the old content in that case, but that is probably okay as this happens when the source file structure has changed.

fix(json): gracefully handle when file changes from dict to list

---

translate/storage/tiki.py

This is the intended behavior and makes redos less likely.

fix(tiki): make the regexp non-greedy

---

tests/translate/storage/test_yaml.py

The tests covered only round-trip, but not the expected parsed values on Python side.

chore(tests): cover expected unit values

---

tests/translate/storage/test_yaml.py
translate/storage/yaml.py

This makes the parsing code match serializing avoiding mixing up the tags.
Fixes #5536

fix(yaml): use language tags when parsing plurals

---

tests/translate/storage/test_yaml.py
translate/storage/yaml.py

Use None instead of blank string for partially translated plurals.
Fixes #5536

fix(ruby yaml): improved serialization of incomplete plurals

---

translate/misc/optrecurse.py

fixes #4979
This is helpful to run pofilter or convert for several directories or several files (and there are not the only ones in the directory).

commands can have arg --input several times

---

tests/xliff_conformance/xliff-core-1.1.xsd
tests/xliff_conformance/xml.xsd

Relying on remote service makes the test fragile. Also the lxml 6.0.0 no longer supports loading remotely, thus failing on these tests.

feat: include xml.xsd for linting xliff

---

tests/translate/storage/test_aresource.py

This was broken at some point in the past, but now works as expected.
Fixes #3281

tests: add test for Android plural handling

---

tests/translate/storage/test_aresource.py
translate/lang/data.py
translate/storage/aresource.py

The content is taken from other/many and the output is sorted again for consistency.
This is a workaround, proper solution will be to allow editing this plural directly.
See https://github.com/WeblateOrg/weblate/issues/7520

feat(android): serialize additional decimal plural

---

.pre-commit-config.yaml
tests/translate/convert/test_rc2po.py
tests/translate/storage/test_po.py
tests/translate/storage/test_wordfast.py
translate/storage/qm.py

I forgot to enable this in the pre-commit configuration in #5679. Meanwhile new typos version was released detecting some additional issues.

feat(ci): actually enable typos spellchecker

---

tests/translate/storage/test_mo.py

The test data are little endian, so the comparison is only useful there.
Fixes #5701

fix(tests): skip comparing to known values on big endian systems

---

tests/translate/services/test_tmserver.py
translate/services/tmserver.py
translate/storage/tmdb.py
translate/tools/pomerge.py
translate/tools/poterminology.py

It already has the %s format string, so explicit conversion is not needed.

chore: remove unnecessary str conversion for logging

---

pyproject.toml
tests/translate/storage/test_po.py
translate/storage/pypo.py

- switch to wcwidth from cwcwidth for newer Unicode support and locale idendependency (fixes #5722)
- do not perform wcwidth on characters only, that doesn't work well for compositing characters
- wrap wcwidth with a safety wrapper to avoid using -1 length and to cache the calculations
- implement breaking of wide strings inside lines for gettext compatibility (fixes #5661)

fix(po): improve text wrapping
